// <auto-generated />
// Generated from inventory: inventory-baylist.json
// Source component: AddBayListDialog
// File: AddBayListDialog.tsx
// Elements: 2 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Baylist;

/// <summary>Page object for the <c>AddBayListDialog</c> component.</summary>
public sealed class AddBayListDialogPage
{
    private readonly IPage _page;
    public AddBayListDialogPage(IPage page) { _page = page; }

    /// <summary>AddBayListDialog: aria-label = "Edit Bay List" (line 286) — globally unique.</summary>
    public ILocator EditBayList => _page.Locator("[aria-label='Edit Bay List']");

    /// <summary>AddBayListDialog: id = "bayListName" (line 304) — globally unique.</summary>
    public ILocator BayListName => _page.Locator("#bayListName");

}