// <auto-generated />
// Generated from inventory: inventory-baylist.json
// Source component: BayList
// File: BayList.tsx
// Elements: 5 (deduped from 5 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Baylist;

/// <summary>Page object for the <c>BayList</c> component.</summary>
public sealed class BayListPage
{
    private readonly IPage _page;
    public BayListPage(IPage page) { _page = page; }

    /// <summary>BayList: placeholder = "Search…" (line 123) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>BayList: placeholder = "Search" (line 128) — globally unique.</summary>
    public ILocator Search2 => _page.Locator("[placeholder='Search']");

    /// <summary>BayList: role = "link" (line 339) — globally unique.</summary>
    public ILocator Link => _page.Locator("[role='link']");

    /// <summary>BayList: aria-label = "Delete" (line 353) — globally unique.</summary>
    public ILocator Delete => _page.Locator("[aria-label='Delete']");

    /// <summary>BayList: h-text = "Bay List" (line 474) — globally unique.</summary>
    public ILocator BayList => _page.Locator("[data-testid='Bay List']");

}