// <auto-generated />
// Generated from inventory: inventory-locations.json
// Source component: AddAndEditLocation
// File: AddAndEditLocation.tsx
// Elements: 8 (deduped from 9 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Locations;

/// <summary>Page object for the <c>AddAndEditLocation</c> component.</summary>
public sealed class AddAndEditLocationPage
{
    private readonly IPage _page;
    public AddAndEditLocationPage(IPage page) { _page = page; }

    /// <summary>AddAndEditLocation: data-testid = "addAndEditLocation-gridData" (line 338) — globally unique.</summary>
    public ILocator AddAndEditLocationGridData => _page.Locator("[data-testid='addAndEditLocation-gridData']");

    /// <summary>AddAndEditLocation: id = "current-active-panel" (line 395) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator CurrentActivePanel => _page.Locator("#current-active-panel");

    /// <summary>AddAndEditLocation: placeholder = "Search…" (line 438) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>AddAndEditLocation: data-testid = "DeleteIcon" (line 550) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator DeleteIcon => _page.Locator("[data-testid='DeleteIcon']");

    /// <summary>AddAndEditLocation: data-testid = "CloseIcon" (line 568) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator CloseIcon => _page.Locator("[data-testid='CloseIcon']");

    /// <summary>AddAndEditLocation: data-testid = "addAndEditLocation-container" (line 820) — globally unique.</summary>
    public ILocator AddAndEditLocationContainer => _page.Locator("[data-testid='addAndEditLocation-container']");

    /// <summary>AddAndEditLocation: id = "locationName" (line 828) — globally unique.</summary>
    public ILocator LocationName => _page.Locator("#locationName");

    /// <summary>AddAndEditLocation: placeholder = "Type and select" (line 850) — globally unique.</summary>
    public ILocator TypeAndSelect => _page.Locator("[placeholder='Type and select']");

}