// <auto-generated />
// Generated from inventory: inventory-locations.json
// Source component: LocationsList
// File: LocationsList.tsx
// Elements: 4 (deduped from 4 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Locations;

/// <summary>Page object for the <c>LocationsList</c> component.</summary>
public sealed class LocationsListPage
{
    private readonly IPage _page;
    public LocationsListPage(IPage page) { _page = page; }

    /// <summary>LocationsList: placeholder = "Search by Location Name" (line 130) — globally unique.</summary>
    public ILocator SearchByLocationName => _page.Locator("[placeholder='Search by Location Name']");

    /// <summary>LocationsList: aria-label = "Clear" (line 137) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>LocationsList: placeholder = "Search…" (line 144) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>LocationsList: data-testid = "close-dialog" (line 633) — globally unique.</summary>
    public ILocator CloseDialog => _page.Locator("[data-testid='close-dialog']");

}