// <auto-generated />
// Generated from inventory: inventory-locations.json
// Source component: ViewLocationsList
// File: (viewlocations)/ViewLocationsList.tsx
// Elements: 8 (deduped from 9 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Locations;

/// <summary>Page object for the <c>ViewLocationsList</c> component.</summary>
public sealed class ViewLocationsListPage
{
    private readonly IPage _page;
    public ViewLocationsListPage(IPage page) { _page = page; }

    /// <summary>ViewLocationsList: data-testid = "viewLocationsList-gridData" (line 157) — globally unique.</summary>
    public ILocator ViewLocationsListGridData => _page.Locator("[data-testid='viewLocationsList-gridData']");

    /// <summary>ViewLocationsList: id = "current-active-panel" (line 192) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator CurrentActivePanel => _page.Locator("#current-active-panel");

    /// <summary>ViewLocationsList: placeholder = "Search…" (line 233) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>ViewLocationsList: aria-label = "Clear" (line 250) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>ViewLocationsList: data-testid = "DeleteIcon" (line 319) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator DeleteIcon => _page.Locator("[data-testid='DeleteIcon']");

    /// <summary>ViewLocationsList: data-testid = "CloseIcon" (line 337) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator CloseIcon => _page.Locator("[data-testid='CloseIcon']");

    /// <summary>ViewLocationsList: data-testid = "viewLocationsList-container" (line 400) — globally unique.</summary>
    public ILocator ViewLocationsListContainer => _page.Locator("[data-testid='viewLocationsList-container']");

    /// <summary>ViewLocationsList: id = "search" (line 408) — globally unique.</summary>
    public ILocator Search2 => _page.Locator("#search");

}