// <auto-generated />
// Generated from inventory: inventory-documenttypes.json
// Source component: AddAndEditDocumentType
// File: (addandeditdocumenttype)/AddAndEditDocumentType.tsx
// Elements: 4 (deduped from 7 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Documenttypes;

/// <summary>Page object for the <c>AddAndEditDocumentType</c> component.</summary>
public sealed class AddAndEditDocumentTypePage
{
    private readonly IPage _page;
    public AddAndEditDocumentTypePage(IPage page) { _page = page; }

    /// <summary>AddAndEditDocumentType: id = "documentType" (line 400) — globally unique.</summary>
    public ILocator DocumentType => _page.Locator("#documentType");

    /// <summary>AddAndEditDocumentType: id = "expirationFrequency" (line 417) — globally unique.</summary>
    public ILocator ExpirationFrequency => _page.Locator("#expirationFrequency");

    /// <summary>AddAndEditDocumentType: placeholder = "Select Period" (line 439) — globally unique.</summary>
    public ILocator SelectPeriod => _page.Locator("[placeholder='Select Period']");

    /// <summary>AddAndEditDocumentType: id = "subTypeInput" (line 472) — globally unique.</summary>
    public ILocator SubTypeInput => _page.Locator("#subTypeInput");

}