// <auto-generated />
// Generated from inventory: inventory-documenttypes.json
// Source component: DocumentTypesList
// File: DocumentTypesList.tsx
// Elements: 3 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Documenttypes;

/// <summary>Page object for the <c>DocumentTypesList</c> component.</summary>
public sealed class DocumentTypesListPage
{
    private readonly IPage _page;
    public DocumentTypesListPage(IPage page) { _page = page; }

    /// <summary>DocumentTypesList: placeholder = "Search by Document Type" (line 129) — globally unique.</summary>
    public ILocator SearchByDocumentType => _page.Locator("[placeholder='Search by Document Type']");

    /// <summary>DocumentTypesList: aria-label = "Clear" (line 136) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>DocumentTypesList: placeholder = "Search…" (line 144) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

}