// <auto-generated />
// Generated from inventory: inventory-reports.json
// Source component: page
// File: address/page.tsx
// Elements: 4 (deduped from 5 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Reports;

/// <summary>Page object for the <c>page</c> component.</summary>
public sealed class pagePage
{
    private readonly IPage _page;
    public pagePage(IPage page) { _page = page; }

    /// <summary>page: h-text = "Address Report" (line 31) — globally unique.</summary>
    public ILocator AddressReport => _page.Locator("[data-testid='Address Report']");

    /// <summary>page: h-text = "Print Reports" (line 89) — globally unique.</summary>
    public ILocator PrintReports => _page.Locator("[data-testid='Print Reports']");

    /// <summary>page: h-text = "Financial Reports" (line 111) — globally unique.</summary>
    public ILocator FinancialReports => _page.Locator("[data-testid='Financial Reports']");

    /// <summary>page: h-text = "Application Reports" (line 145) — globally unique.</summary>
    public ILocator ApplicationReports => _page.Locator("[data-testid='Application Reports']");

}