// <auto-generated />
// Generated from inventory: inventory-roleandpermission.json
// Source component: NewUserRole
// File: NewUserRole.tsx
// Elements: 3 (deduped from 5 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Roleandpermission;

/// <summary>Page object for the <c>NewUserRole</c> component.</summary>
public sealed class NewUserRolePage
{
    private readonly IPage _page;
    public NewUserRolePage(IPage page) { _page = page; }

    /// <summary>NewUserRole: role = "combobox" (line 92) — globally unique.</summary>
    public ILocator Combobox => _page.Locator("[role='combobox']");

    /// <summary>NewUserRole: id = "name" (line 427) — globally unique.</summary>
    public ILocator Name => _page.Locator("#name");

    /// <summary>NewUserRole: id = "description" (line 449) — globally unique.</summary>
    public ILocator Description => _page.Locator("#description");

}