// <auto-generated />
// Generated from inventory: inventory-roleandpermission.json
// Source component: RoleAndPermissionList
// File: RoleAndPermissionList.tsx
// Elements: 3 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Roleandpermission;

/// <summary>Page object for the <c>RoleAndPermissionList</c> component.</summary>
public sealed class RoleAndPermissionListPage
{
    private readonly IPage _page;
    public RoleAndPermissionListPage(IPage page) { _page = page; }

    /// <summary>RoleAndPermissionList: placeholder = "Search by Role" (line 115) — globally unique.</summary>
    public ILocator SearchByRole => _page.Locator("[placeholder='Search by Role']");

    /// <summary>RoleAndPermissionList: aria-label = "Clear" (line 121) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>RoleAndPermissionList: placeholder = "Search…" (line 182) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

}