// <auto-generated />
// Generated from inventory: inventory-alertsandtooltips.json
// Source component: page
// File: page.tsx
// Elements: 7 (deduped from 9 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Alertsandtooltips;

/// <summary>Page object for the <c>page</c> component.</summary>
public sealed class pagePage
{
    private readonly IPage _page;
    public pagePage(IPage page) { _page = page; }

    /// <summary>page: id = "experianMessage" (line 303) — globally unique.</summary>
    public ILocator ExperianMessage => _page.Locator("#experianMessage");

    /// <summary>page: data-testid = "experianMessageInput" (line 318) — globally unique.</summary>
    public ILocator ExperianMessageInput => _page.Locator("[data-testid='experianMessageInput']");

    /// <summary>page: id = "correspondenceAddress" (line 357) — globally unique.</summary>
    public ILocator CorrespondenceAddress => _page.Locator("#correspondenceAddress");

    /// <summary>page: data-testid = "correspondenceAddressInput" (line 375) — globally unique.</summary>
    public ILocator CorrespondenceAddressInput => _page.Locator("[data-testid='correspondenceAddressInput']");

    /// <summary>page: data-testid = "customerNotificationSwitch" (line 394) — globally unique.</summary>
    public ILocator CustomerNotificationSwitch => _page.Locator("[data-testid='customerNotificationSwitch']");

    /// <summary>page: h-text = "Alerts And Tooltips" (line 457) — globally unique.</summary>
    public ILocator AlertsAndTooltips => _page.Locator("[data-testid='Alerts And Tooltips']");

    /// <summary>page: data-testid = "unsaved-dialog-close" (line 512) — globally unique.</summary>
    public ILocator UnsavedDialogClose => _page.Locator("[data-testid='unsaved-dialog-close']");

}