// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: AddApplicants
// File: AddApplicants.tsx
// Elements: 7 (deduped from 13 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>AddApplicants</c> component.</summary>
public sealed class AddApplicantsPage
{
    private readonly IPage _page;
    public AddApplicantsPage(IPage page) { _page = page; }

    /// <summary>AddApplicants: placeholder = "Select a title" (line 385) — globally unique.</summary>
    public ILocator SelectATitle => _page.Locator("[placeholder='Select a title']");

    /// <summary>AddApplicants: id = "firstName" (line 398) — globally unique.</summary>
    public ILocator FirstName => _page.Locator("#firstName");

    /// <summary>AddApplicants: id = "lastName" (line 422) — globally unique.</summary>
    public ILocator LastName => _page.Locator("#lastName");

    /// <summary>AddApplicants: id = "userName" (line 452) — globally unique.</summary>
    public ILocator UserName => _page.Locator("#userName");

    /// <summary>AddApplicants: id = "emailAddress" (line 469) — globally unique.</summary>
    public ILocator EmailAddress => _page.Locator("#emailAddress");

    /// <summary>AddApplicants: id = "mobileNumber" (line 527) — globally unique.</summary>
    public ILocator MobileNumber => _page.Locator("#mobileNumber");

    /// <summary>AddApplicants: id = "alternateNumber" (line 580) — globally unique.</summary>
    public ILocator AlternateNumber => _page.Locator("#alternateNumber");

}