// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: AddBlueBadge
// File: AddBlueBadge.tsx
// Elements: 2 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>AddBlueBadge</c> component.</summary>
public sealed class AddBlueBadgePage
{
    private readonly IPage _page;
    public AddBlueBadgePage(IPage page) { _page = page; }

    /// <summary>AddBlueBadge: id = "blueBadgeNumber" (line 145) — globally unique.</summary>
    public ILocator BlueBadgeNumber => _page.Locator("#blueBadgeNumber");

    /// <summary>AddBlueBadge: data-testid = "vehicle-logo" (line 191) — WARNING: value reused 10x — scope to parent if needed.</summary>
    public ILocator VehicleLogo => _page.Locator("[data-testid='vehicle-logo']");

}