// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: AddVehicle
// File: (vechicle)/AddVehicle.tsx
// Elements: 13 (deduped from 15 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>AddVehicle</c> component.</summary>
public sealed class AddVehiclePage
{
    private readonly IPage _page;
    public AddVehiclePage(IPage page) { _page = page; }

    /// <summary>AddVehicle: name = "VehicleType" (line 804) — globally unique.</summary>
    public ILocator VehicleType => _page.Locator("[name='VehicleType']");

    /// <summary>AddVehicle: id = "registrationNumber" (line 829) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator RegistrationNumber => _page.Locator("#registrationNumber");

    /// <summary>AddVehicle: placeholder = "Select vehicle category" (line 923) — globally unique.</summary>
    public ILocator SelectVehicleCategory => _page.Locator("[placeholder='Select vehicle category']");

    /// <summary>AddVehicle: placeholder = "Select fuel type" (line 957) — globally unique.</summary>
    public ILocator SelectFuelType => _page.Locator("[placeholder='Select fuel type']");

    /// <summary>AddVehicle: placeholder = "Select make" (line 990) — globally unique.</summary>
    public ILocator SelectMake => _page.Locator("[placeholder='Select make']");

    /// <summary>AddVehicle: placeholder = "Select model" (line 1022) — globally unique.</summary>
    public ILocator SelectModel => _page.Locator("[placeholder='Select model']");

    /// <summary>AddVehicle: placeholder = "Select color" (line 1054) — globally unique.</summary>
    public ILocator SelectColor => _page.Locator("[placeholder='Select color']");

    /// <summary>AddVehicle: placeholder = "Select CO2 emission" (line 1086) — globally unique.</summary>
    public ILocator SelectCO2Emission => _page.Locator("[placeholder='Select CO2 emission']");

    /// <summary>AddVehicle: name = "isEuroStandard" (line 1109) — globally unique.</summary>
    public ILocator IsEuroStandard => _page.Locator("[name='isEuroStandard']");

    /// <summary>AddVehicle: name = "isregisteredKeeper" (line 1129) — globally unique.</summary>
    public ILocator IsregisteredKeeper => _page.Locator("[name='isregisteredKeeper']");

    /// <summary>AddVehicle: data-testid = "vehicle-logo" (line 1192) — WARNING: value reused 10x — scope to parent if needed.</summary>
    public ILocator VehicleLogo => _page.Locator("[data-testid='vehicle-logo']");

    /// <summary>AddVehicle: id = "nickName" (line 1251) — globally unique.</summary>
    public ILocator NickName => _page.Locator("#nickName");

    /// <summary>AddVehicle: name = "isfavoriteVehicle" (line 1267) — globally unique.</summary>
    public ILocator IsfavoriteVehicle => _page.Locator("[name='isfavoriteVehicle']");

}