// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: ApplicantSendEmail
// File: (applicantemail)/applicantsendemail/ApplicantSendEmail.tsx
// Elements: 5 (deduped from 7 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>ApplicantSendEmail</c> component.</summary>
public sealed class ApplicantSendEmailPage
{
    private readonly IPage _page;
    public ApplicantSendEmailPage(IPage page) { _page = page; }

    /// <summary>ApplicantSendEmail: id = "receiverEmail" (line 568) — globally unique.</summary>
    public ILocator ReceiverEmail => _page.Locator("#receiverEmail");

    /// <summary>ApplicantSendEmail: placeholder = "Select sender email" (line 612) — globally unique.</summary>
    public ILocator SelectSenderEmail => _page.Locator("[placeholder='Select sender email']");

    /// <summary>ApplicantSendEmail: placeholder = "Select template" (line 633) — globally unique.</summary>
    public ILocator SelectTemplate => _page.Locator("[placeholder='Select template']");

    /// <summary>ApplicantSendEmail: id = "subject" (line 649) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Subject => _page.Locator("#subject");

    /// <summary>ApplicantSendEmail: data-testid = "vehicle-logo" (line 691) — WARNING: value reused 10x — scope to parent if needed.</summary>
    public ILocator VehicleLogo => _page.Locator("[data-testid='vehicle-logo']");

}