// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: ApplicantEmailList
// File: (applicantemail)/ApplicantEmailList.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>ApplicantEmailList</c> component.</summary>
public sealed class ApplicantEmailListPage
{
    private readonly IPage _page;
    public ApplicantEmailListPage(IPage page) { _page = page; }

    /// <summary>ApplicantEmailList: placeholder = "Search…" (line 115) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>ApplicantEmailList: aria-label = "Clear" (line 121) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

}