// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: ApplicantEmailBroadcasting
// File: (applicantemailbroadcasting)/ApplicantEmailBroadcasting.tsx
// Elements: 4 (deduped from 6 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>ApplicantEmailBroadcasting</c> component.</summary>
public sealed class ApplicantEmailBroadcastingPage
{
    private readonly IPage _page;
    public ApplicantEmailBroadcastingPage(IPage page) { _page = page; }

    /// <summary>ApplicantEmailBroadcasting: id = "search" (line 717) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Search => _page.Locator("#search");

    /// <summary>ApplicantEmailBroadcasting: placeholder = "Select" (line 860) — globally unique.</summary>
    public ILocator Select => _page.Locator("[placeholder='Select']");

    /// <summary>ApplicantEmailBroadcasting: id = "subject" (line 897) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Subject => _page.Locator("#subject");

    /// <summary>ApplicantEmailBroadcasting: data-testid = "vehicle-logo" (line 943) — WARNING: value reused 10x — scope to parent if needed.</summary>
    public ILocator VehicleLogo => _page.Locator("[data-testid='vehicle-logo']");

}