// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: AuditLogList
// File: auditlog/AuditLogList.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>AuditLogList</c> component.</summary>
public sealed class AuditLogListPage
{
    private readonly IPage _page;
    public AuditLogListPage(IPage page) { _page = page; }

    /// <summary>AuditLogList: placeholder = "Search…" (line 120) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>AuditLogList: aria-label = "Clear" (line 126) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

}