// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: DocumentList
// File: (document)/DocumentList.tsx
// Elements: 2 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>DocumentList</c> component.</summary>
public sealed class DocumentListPage
{
    private readonly IPage _page;
    public DocumentListPage(IPage page) { _page = page; }

    /// <summary>DocumentList: aria-label = "Clear" (line 244) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>DocumentList: data-testid = "vehicle-logo" (line 402) — WARNING: value reused 10x — scope to parent if needed.</summary>
    public ILocator VehicleLogo => _page.Locator("[data-testid='vehicle-logo']");

}