// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: DraftApplicationsList
// File: DraftApplicationsList.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>DraftApplicationsList</c> component.</summary>
public sealed class DraftApplicationsListPage
{
    private readonly IPage _page;
    public DraftApplicationsListPage(IPage page) { _page = page; }

    /// <summary>DraftApplicationsList: h-text = "No Draft Applications" (line 141) — globally unique.</summary>
    public ILocator NoDraftApplications => _page.Locator("[data-testid='No Draft Applications']");

}