// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: EditVehicle
// File: (vechicle)/EditVehicle.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>EditVehicle</c> component.</summary>
public sealed class EditVehiclePage
{
    private readonly IPage _page;
    public EditVehiclePage(IPage page) { _page = page; }

    /// <summary>EditVehicle: data-testid = "vehicle-logo" (line 289) — WARNING: value reused 10x — scope to parent if needed.</summary>
    public ILocator VehicleLogo => _page.Locator("[data-testid='vehicle-logo']");

}