// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: EditApplicants
// File: EditApplicants.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>EditApplicants</c> component.</summary>
public sealed class EditApplicantsPage
{
    private readonly IPage _page;
    public EditApplicantsPage(IPage page) { _page = page; }

    /// <summary>EditApplicants: h-text = "General" (line 269) — globally unique.</summary>
    public ILocator General => _page.Locator("[data-testid='General']");

    /// <summary>EditApplicants: h-text = "Blue Badge" (line 374) — globally unique.</summary>
    public ILocator BlueBadge => _page.Locator("[data-testid='Blue Badge']");

}