// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: page
// File: page.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>page</c> component.</summary>
public sealed class pagePage
{
    private readonly IPage _page;
    public pagePage(IPage page) { _page = page; }

    /// <summary>page: h-text = "Purchase Status" (line 282) — globally unique.</summary>
    public ILocator PurchaseStatus => _page.Locator("[data-testid='Purchase Status']");

    /// <summary>page: h-text = "New Application" (line 297) — globally unique.</summary>
    public ILocator NewApplication => _page.Locator("[data-testid='New Application']");

}