// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: PermitDocument
// File: (permitdocument)/PermitDocument.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>PermitDocument</c> component.</summary>
public sealed class PermitDocumentPage
{
    private readonly IPage _page;
    public PermitDocumentPage(IPage page) { _page = page; }

    /// <summary>PermitDocument: data-testid = "vehicle-logo" (line 546) — WARNING: value reused 10x — scope to parent if needed.</summary>
    public ILocator VehicleLogo => _page.Locator("[data-testid='vehicle-logo']");

}