// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: PermitVehicle
// File: (permitvehicle)/PermitVehicle.tsx
// Elements: 3 (deduped from 4 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>PermitVehicle</c> component.</summary>
public sealed class PermitVehiclePage
{
    private readonly IPage _page;
    public PermitVehiclePage(IPage page) { _page = page; }

    /// <summary>PermitVehicle: data-testid = "vehicle-logo" (line 284) — WARNING: value reused 10x — scope to parent if needed.</summary>
    public ILocator VehicleLogo => _page.Locator("[data-testid='vehicle-logo']");

    /// <summary>PermitVehicle: id = "search" (line 401) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Search => _page.Locator("#search");

    /// <summary>PermitVehicle: data-testid = "star-icon" (line 463) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator StarIcon => _page.Locator("[data-testid='star-icon']");

}