// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: TemporaryVehiclePanel
// File: (vechicle)/TemporaryVehiclePanel.tsx
// Elements: 1 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>TemporaryVehiclePanel</c> component.</summary>
public sealed class TemporaryVehiclePanelPage
{
    private readonly IPage _page;
    public TemporaryVehiclePanelPage(IPage page) { _page = page; }

    /// <summary>TemporaryVehiclePanel: id = "registrationNumber" (line 123) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator RegistrationNumber => _page.Locator("#registrationNumber");

}