// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: VehiclesList
// File: VehiclesList.tsx
// Elements: 6 (deduped from 6 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>VehiclesList</c> component.</summary>
public sealed class VehiclesListPage
{
    private readonly IPage _page;
    public VehiclesListPage(IPage page) { _page = page; }

    /// <summary>VehiclesList: placeholder = "Search…" (line 182) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>VehiclesList: aria-label = "Clear" (line 187) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>VehiclesList: data-testid = "vehicle-logo" (line 301) — WARNING: value reused 10x — scope to parent if needed.</summary>
    public ILocator VehicleLogo => _page.Locator("[data-testid='vehicle-logo']");

    /// <summary>VehiclesList: data-testid = "star-icon" (line 316) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator StarIcon => _page.Locator("[data-testid='star-icon']");

    /// <summary>VehiclesList: data-testid = "vehicles-list-page" (line 921) — globally unique.</summary>
    public ILocator VehiclesListPage => _page.Locator("[data-testid='vehicles-list-page']");

    /// <summary>VehiclesList: data-testid = "vehicles-list-grid" (line 981) — globally unique.</summary>
    public ILocator VehiclesListGrid => _page.Locator("[data-testid='vehicles-list-grid']");

}