// <auto-generated />
// Generated from inventory: inventory-applicants.json
// Source component: ViewApplicantsList
// File: ViewApplicantsList.tsx
// Elements: 7 (deduped from 8 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applicants;

/// <summary>Page object for the <c>ViewApplicantsList</c> component.</summary>
public sealed class ViewApplicantsListPage
{
    private readonly IPage _page;
    public ViewApplicantsListPage(IPage page) { _page = page; }

    /// <summary>ViewApplicantsList: data-testid = "viewApplicantsListTab-gridData" (line 331) — globally unique.</summary>
    public ILocator ViewApplicantsListTabGridData => _page.Locator("[data-testid='viewApplicantsListTab-gridData']");

    /// <summary>ViewApplicantsList: id = "current-active-panel" (line 373) — globally unique.</summary>
    public ILocator CurrentActivePanel => _page.Locator("#current-active-panel");

    /// <summary>ViewApplicantsList: aria-label = "Clear" (line 416) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>ViewApplicantsList: data-testid = "DeleteIcon" (line 485) — globally unique.</summary>
    public ILocator DeleteIcon => _page.Locator("[data-testid='DeleteIcon']");

    /// <summary>ViewApplicantsList: data-testid = "CloseIcon" (line 503) — globally unique.</summary>
    public ILocator CloseIcon => _page.Locator("[data-testid='CloseIcon']");

    /// <summary>ViewApplicantsList: data-testid = "viewApplicantsListTab-container" (line 555) — globally unique.</summary>
    public ILocator ViewApplicantsListTabContainer => _page.Locator("[data-testid='viewApplicantsListTab-container']");

    /// <summary>ViewApplicantsList: data-testid = "viewApplicantsListTab-container-slidingPanel" (line 577) — globally unique.</summary>
    public ILocator ViewApplicantsListTabContainerSlidingPanel => _page.Locator("[data-testid='viewApplicantsListTab-container-slidingPanel']");

}