// <auto-generated />
// Generated from inventory: inventory-SpecialEvents.json
// Source component: AddSpecialEvent
// File: AddSpecialEvent.tsx
// Elements: 7 (deduped from 7 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.SpecialEvents;

/// <summary>Page object for the <c>AddSpecialEvent</c> component.</summary>
public sealed class AddSpecialEventPage
{
    private readonly IPage _page;
    public AddSpecialEventPage(IPage page) { _page = page; }

    /// <summary>AddSpecialEvent: data-testid = "addAndEditLocation-gridData" (line 423) — globally unique.</summary>
    public ILocator AddAndEditLocationGridData => _page.Locator("[data-testid='addAndEditLocation-gridData']");

    /// <summary>AddSpecialEvent: id = "current-active-panel" (line 474) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator CurrentActivePanel => _page.Locator("#current-active-panel");

    /// <summary>AddSpecialEvent: placeholder = "Search…" (line 512) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>AddSpecialEvent: data-testid = "DeleteIcon" (line 650) — globally unique.</summary>
    public ILocator DeleteIcon => _page.Locator("[data-testid='DeleteIcon']");

    /// <summary>AddSpecialEvent: data-testid = "CloseIcon" (line 668) — globally unique.</summary>
    public ILocator CloseIcon => _page.Locator("[data-testid='CloseIcon']");

    /// <summary>AddSpecialEvent: id = "eventName" (line 1266) — globally unique.</summary>
    public ILocator EventName => _page.Locator("#eventName");

    /// <summary>AddSpecialEvent: placeholder = "Type and select" (line 1290) — globally unique.</summary>
    public ILocator TypeAndSelect => _page.Locator("[placeholder='Type and select']");

}