// <auto-generated />
// Generated from inventory: inventory-SpecialEvents.json
// Source component: EditZonePermission
// File: (permissions)/EditZonePermission.tsx
// Elements: 4 (deduped from 5 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.SpecialEvents;

/// <summary>Page object for the <c>EditZonePermission</c> component.</summary>
public sealed class EditZonePermissionPage
{
    private readonly IPage _page;
    public EditZonePermissionPage(IPage page) { _page = page; }

    /// <summary>EditZonePermission: id = "zone" (line 327) — globally unique.</summary>
    public ILocator Zone => _page.Locator("#zone");

    /// <summary>EditZonePermission: id = "userZone" (line 381) — globally unique.</summary>
    public ILocator UserZone => _page.Locator("#userZone");

    /// <summary>EditZonePermission: id = "voucher" (line 436) — globally unique.</summary>
    public ILocator Voucher => _page.Locator("#voucher");

    /// <summary>EditZonePermission: id = "blueBadge" (line 489) — globally unique.</summary>
    public ILocator BlueBadge => _page.Locator("#blueBadge");

}