// <auto-generated />
// Generated from inventory: inventory-SpecialEvents.json
// Source component: page
// File: page.tsx
// Elements: 4 (deduped from 5 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.SpecialEvents;

/// <summary>Page object for the <c>page</c> component.</summary>
public sealed class pagePage
{
    private readonly IPage _page;
    public pagePage(IPage page) { _page = page; }

    /// <summary>page: placeholder = "Search…" (line 270) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>page: id = "search" (line 909) — globally unique.</summary>
    public ILocator Search2 => _page.Locator("#search");

    /// <summary>page: data-testid = "viewSpecialEventsList-gridData" (line 944) — globally unique.</summary>
    public ILocator ViewSpecialEventsListGridData => _page.Locator("[data-testid='viewSpecialEventsList-gridData']");

    /// <summary>page: id = "current-active-panel" (line 999) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator CurrentActivePanel => _page.Locator("#current-active-panel");

}