// <auto-generated />
// Generated from inventory: inventory-SpecialEvents.json
// Source component: PermissionsList
// File: (permissions)/PermissionsList.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.SpecialEvents;

/// <summary>Page object for the <c>PermissionsList</c> component.</summary>
public sealed class PermissionsListPage
{
    private readonly IPage _page;
    public PermissionsListPage(IPage page) { _page = page; }

    /// <summary>PermissionsList: placeholder = "Search…" (line 88) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>PermissionsList: aria-label = "Clear" (line 92) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

}