// <auto-generated />
// Generated from inventory: inventory-SpecialEvents.json
// Source component: SpecialEventList
// File: SpecialEventList.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.SpecialEvents;

/// <summary>Page object for the <c>SpecialEventList</c> component.</summary>
public sealed class SpecialEventListPage
{
    private readonly IPage _page;
    public SpecialEventListPage(IPage page) { _page = page; }

    /// <summary>SpecialEventList: placeholder = "Search…" (line 110) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>SpecialEventList: aria-label = "Clear" (line 115) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

}