// <auto-generated />
// Generated from inventory: inventory-systemusers.json
// Source component: AddSystemUser
// File: AddSystemUser.tsx
// Elements: 8 (deduped from 13 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Systemusers;

/// <summary>Page object for the <c>AddSystemUser</c> component.</summary>
public sealed class AddSystemUserPage
{
    private readonly IPage _page;
    public AddSystemUserPage(IPage page) { _page = page; }

    /// <summary>AddSystemUser: placeholder = "Enter First Name" (line 690) — globally unique.</summary>
    public ILocator EnterFirstName => _page.Locator("[placeholder='Enter First Name']");

    /// <summary>AddSystemUser: id = "firstName" (line 694) — globally unique.</summary>
    public ILocator FirstName => _page.Locator("#firstName");

    /// <summary>AddSystemUser: id = "lastName" (line 722) — globally unique.</summary>
    public ILocator LastName => _page.Locator("#lastName");

    /// <summary>AddSystemUser: id = "emailAddress" (line 749) — globally unique.</summary>
    public ILocator EmailAddress => _page.Locator("#emailAddress");

    /// <summary>AddSystemUser: placeholder = "Select" (line 778) — globally unique.</summary>
    public ILocator Select => _page.Locator("[placeholder='Select']");

    /// <summary>AddSystemUser: id = "mobileNumber" (line 796) — globally unique.</summary>
    public ILocator MobileNumber => _page.Locator("#mobileNumber");

    /// <summary>AddSystemUser: id = "ddi" (line 874) — globally unique.</summary>
    public ILocator Ddi => _page.Locator("#ddi");

    /// <summary>AddSystemUser: id = "pin" (line 902) — globally unique.</summary>
    public ILocator Pin => _page.Locator("#pin");

}