// <auto-generated />
// Generated from inventory: inventory-systemusers.json
// Source component: SystemUserAuditLogList
// File: (systemuserauditloglist)/SystemUserAuditLogList.tsx
// Elements: 1 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Systemusers;

/// <summary>Page object for the <c>SystemUserAuditLogList</c> component.</summary>
public sealed class SystemUserAuditLogListPage
{
    private readonly IPage _page;
    public SystemUserAuditLogListPage(IPage page) { _page = page; }

    /// <summary>SystemUserAuditLogList: aria-label = "Clear" (line 105) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

}