// <auto-generated />
// Generated from inventory: inventory-systemusers.json
// Source component: SystemUsersList
// File: SystemUsersList.tsx
// Elements: 3 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Systemusers;

/// <summary>Page object for the <c>SystemUsersList</c> component.</summary>
public sealed class SystemUsersListPage
{
    private readonly IPage _page;
    public SystemUsersListPage(IPage page) { _page = page; }

    /// <summary>SystemUsersList: placeholder = "Search by First Name, Last Name" (line 94) — globally unique.</summary>
    public ILocator SearchByFirstNameLastName => _page.Locator("[placeholder='Search by First Name, Last Name']");

    /// <summary>SystemUsersList: aria-label = "Clear" (line 98) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>SystemUsersList: placeholder = "Search…" (line 158) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

}