// <auto-generated />
// Generated from inventory: inventory-physicalpermission.json
// Source component: PhysicalPermissionList
// File: PhysicalPermissionList.tsx
// Elements: 3 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Physicalpermission;

/// <summary>Page object for the <c>PhysicalPermissionList</c> component.</summary>
public sealed class PhysicalPermissionListPage
{
    private readonly IPage _page;
    public PhysicalPermissionListPage(IPage page) { _page = page; }

    /// <summary>PhysicalPermissionList: placeholder = "Search by Reference Number, Applicant Name" (line 484) — globally unique.</summary>
    public ILocator SearchByReferenceNumberApplicantName => _page.Locator("[placeholder='Search by Reference Number, Applicant Name']");

    /// <summary>PhysicalPermissionList: aria-label = "Clear" (line 490) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>PhysicalPermissionList: placeholder = "Search…" (line 614) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

}