// <auto-generated />
// Generated from inventory: inventory-streets.json
// Source component: BlackList
// File: BlackList.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Streets;

/// <summary>Page object for the <c>BlackList</c> component.</summary>
public sealed class BlackListPage
{
    private readonly IPage _page;
    public BlackListPage(IPage page) { _page = page; }

    /// <summary>BlackList: placeholder = "Search…" (line 272) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

}