// <auto-generated />
// Generated from inventory: inventory-streets.json
// Source component: BlackListProperty
// File: BlackListProperty.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Streets;

/// <summary>Page object for the <c>BlackListProperty</c> component.</summary>
public sealed class BlackListPropertyPage
{
    private readonly IPage _page;
    public BlackListPropertyPage(IPage page) { _page = page; }

    /// <summary>BlackListProperty: placeholder = "Search…" (line 235) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>BlackListProperty: placeholder = "Select Range" (line 810) — globally unique.</summary>
    public ILocator SelectRange => _page.Locator("[placeholder='Select Range']");

}