// <auto-generated />
// Generated from inventory: inventory-streets.json
// Source component: page
// File: page.tsx
// Elements: 2 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Streets;

/// <summary>Page object for the <c>page</c> component.</summary>
public sealed class pagePage
{
    private readonly IPage _page;
    public pagePage(IPage page) { _page = page; }

    /// <summary>page: aria-label = "Clear" (line 701) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>page: placeholder = "Select Range" (line 820) — globally unique.</summary>
    public ILocator SelectRange => _page.Locator("[placeholder='Select Range']");

}