// <auto-generated />
// Generated from inventory: inventory-streets.json
// Source component: StreetsSliderPage
// File: StreetsSliderPage.tsx
// Elements: 10 (deduped from 15 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Streets;

/// <summary>Page object for the <c>StreetsSliderPage</c> component.</summary>
public sealed class StreetsSliderPagePage
{
    private readonly IPage _page;
    public StreetsSliderPagePage(IPage page) { _page = page; }

    /// <summary>StreetsSliderPage: placeholder = "Enter Street Name" (line 611) — globally unique.</summary>
    public ILocator EnterStreetName => _page.Locator("[placeholder='Enter Street Name']");

    /// <summary>StreetsSliderPage: id = "steetName" (line 617) — globally unique.</summary>
    public ILocator SteetName => _page.Locator("#steetName");

    /// <summary>StreetsSliderPage: id = "usrn" (line 636) — globally unique.</summary>
    public ILocator Usrn => _page.Locator("#usrn");

    /// <summary>StreetsSliderPage: placeholder = "Town Name" (line 729) — globally unique.</summary>
    public ILocator TownName => _page.Locator("[placeholder='Town Name']");

    /// <summary>StreetsSliderPage: id = "firstName" (line 744) — globally unique.</summary>
    public ILocator FirstName => _page.Locator("#firstName");

    /// <summary>StreetsSliderPage: id = "propertyName" (line 790) — globally unique.</summary>
    public ILocator PropertyName => _page.Locator("#propertyName");

    /// <summary>StreetsSliderPage: id = "postcode" (line 822) — globally unique.</summary>
    public ILocator Postcode => _page.Locator("#postcode");

    /// <summary>StreetsSliderPage: id = "uprn" (line 838) — globally unique.</summary>
    public ILocator Uprn => _page.Locator("#uprn");

    /// <summary>StreetsSliderPage: id = "permissionLimit" (line 874) — globally unique.</summary>
    public ILocator PermissionLimit => _page.Locator("#permissionLimit");

    /// <summary>StreetsSliderPage: placeholder = "Permission Limit" (line 880) — globally unique.</summary>
    public ILocator PermissionLimit2 => _page.Locator("[placeholder='Permission Limit']");

}