// <auto-generated />
// Generated from inventory: inventory-streets.json
// Source component: WhiteList
// File: WhiteList.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Streets;

/// <summary>Page object for the <c>WhiteList</c> component.</summary>
public sealed class WhiteListPage
{
    private readonly IPage _page;
    public WhiteListPage(IPage page) { _page = page; }

    /// <summary>WhiteList: placeholder = "Search…" (line 303) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>WhiteList: placeholder = "Select Range" (line 803) — globally unique.</summary>
    public ILocator SelectRange => _page.Locator("[placeholder='Select Range']");

}