// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: AutoApprovalSettings
// File: (permissionBuilder)/AutoApprovalSettings.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>AutoApprovalSettings</c> component.</summary>
public sealed class AutoApprovalSettingsPage
{
    private readonly IPage _page;
    public AutoApprovalSettingsPage(IPage page) { _page = page; }

    /// <summary>AutoApprovalSettings: data-testid = "paymentSettings-container" (line 120) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator PaymentSettingsContainer => _page.Locator("[data-testid='paymentSettings-container']");

}