// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: BasicInformation
// File: (permissionBuilder)/BasicInformation.tsx
// Elements: 7 (deduped from 9 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>BasicInformation</c> component.</summary>
public sealed class BasicInformationPage
{
    private readonly IPage _page;
    public BasicInformationPage(IPage page) { _page = page; }

    /// <summary>BasicInformation: data-testid = "generalSettings-container" (line 431) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator GeneralSettingsContainer => _page.Locator("[data-testid='generalSettings-container']");

    /// <summary>BasicInformation: id = "permissionName" (line 445) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator PermissionName => _page.Locator("#permissionName");

    /// <summary>BasicInformation: placeholder = "Select" (line 476) — globally unique.</summary>
    public ILocator Select => _page.Locator("[placeholder='Select']");

    /// <summary>BasicInformation: data-testid = "permissionTypeAutoComplete" (line 482) — globally unique.</summary>
    public ILocator PermissionTypeAutoComplete => _page.Locator("[data-testid='permissionTypeAutoComplete']");

    /// <summary>BasicInformation: data-testid = "permissionGroupAutoComplete" (line 507) — globally unique.</summary>
    public ILocator PermissionGroupAutoComplete => _page.Locator("[data-testid='permissionGroupAutoComplete']");

    /// <summary>BasicInformation: data-testid = "permissionCategoryAutoComplete" (line 531) — globally unique.</summary>
    public ILocator PermissionCategoryAutoComplete => _page.Locator("[data-testid='permissionCategoryAutoComplete']");

    /// <summary>BasicInformation: id = "description" (line 544) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Description => _page.Locator("#description");

}