// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: BuilderList
// File: BuilderList.tsx
// Elements: 3 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>BuilderList</c> component.</summary>
public sealed class BuilderListPage
{
    private readonly IPage _page;
    public BuilderListPage(IPage page) { _page = page; }

    /// <summary>BuilderList: placeholder = "Search…" (line 147) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>BuilderList: placeholder = "Permission name/Type/Group" (line 158) — globally unique.</summary>
    public ILocator PermissionNameTypeGroup => _page.Locator("[placeholder='Permission name/Type/Group']");

    /// <summary>BuilderList: aria-label = "Clear" (line 165) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

}