// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: DiscountSettings
// File: (permissionBuilder)/DiscountSettings.tsx
// Elements: 4 (deduped from 5 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>DiscountSettings</c> component.</summary>
public sealed class DiscountSettingsPage
{
    private readonly IPage _page;
    public DiscountSettingsPage(IPage page) { _page = page; }

    /// <summary>DiscountSettings: data-testid = "discountSettings-container" (line 326) — globally unique.</summary>
    public ILocator DiscountSettingsContainer => _page.Locator("[data-testid='discountSettings-container']");

    /// <summary>DiscountSettings: id = "blueBatchDiscountValue" (line 348) — globally unique.</summary>
    public ILocator BlueBatchDiscountValue => _page.Locator("#blueBatchDiscountValue");

    /// <summary>DiscountSettings: id = "pensionDiscountValue" (line 486) — globally unique.</summary>
    public ILocator PensionDiscountValue => _page.Locator("#pensionDiscountValue");

    /// <summary>DiscountSettings: id = "paymentSettingsHelperText" (line 624) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator PaymentSettingsHelperText => _page.Locator("#paymentSettingsHelperText");

}