// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: EditPermissionsBuilderForm
// File: (permissionBuilder)/EditPermissionsBuilderForm.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>EditPermissionsBuilderForm</c> component.</summary>
public sealed class EditPermissionsBuilderFormPage
{
    private readonly IPage _page;
    public EditPermissionsBuilderFormPage(IPage page) { _page = page; }

    /// <summary>EditPermissionsBuilderForm: id = "permissionCategoryHeader" (line 854) — globally unique.</summary>
    public ILocator PermissionCategoryHeader => _page.Locator("#permissionCategoryHeader");

    /// <summary>EditPermissionsBuilderForm: data-testid = "edit-permission-builder-form-container" (line 1326) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator EditPermissionBuilderFormContainer => _page.Locator("[data-testid='edit-permission-builder-form-container']");

}