// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: EditPermissionBuilderForm
// File: (permissionBuilder)/EditPermissionBuilderForm.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>EditPermissionBuilderForm</c> component.</summary>
public sealed class EditPermissionBuilderFormPage
{
    private readonly IPage _page;
    public EditPermissionBuilderFormPage(IPage page) { _page = page; }

    /// <summary>EditPermissionBuilderForm: data-testid = "edit-permission-builder-form-gridData" (line 71) — globally unique.</summary>
    public ILocator EditPermissionBuilderFormGridData => _page.Locator("[data-testid='edit-permission-builder-form-gridData']");

    /// <summary>EditPermissionBuilderForm: data-testid = "edit-permission-builder-form-container" (line 124) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator EditPermissionBuilderFormContainer => _page.Locator("[data-testid='edit-permission-builder-form-container']");

}