// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: EmailTemplates
// File: (permissionBuilder)/EmailTemplates.tsx
// Elements: 3 (deduped from 4 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>EmailTemplates</c> component.</summary>
public sealed class EmailTemplatesPage
{
    private readonly IPage _page;
    public EmailTemplatesPage(IPage page) { _page = page; }

    /// <summary>EmailTemplates: data-testid = "emailTemplates-container" (line 298) — globally unique.</summary>
    public ILocator EmailTemplatesContainer => _page.Locator("[data-testid='emailTemplates-container']");

    /// <summary>EmailTemplates: placeholder = "Select a title" (line 362) — globally unique.</summary>
    public ILocator SelectATitle => _page.Locator("[placeholder='Select a title']");

    /// <summary>EmailTemplates: id = "emailEventData" (line 382) — globally unique.</summary>
    public ILocator EmailEventData => _page.Locator("#emailEventData");

}