// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: FixedDurationPricing
// File: (permissionBuilder)/FixedDurationPricing.tsx
// Elements: 3 (deduped from 4 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>FixedDurationPricing</c> component.</summary>
public sealed class FixedDurationPricingPage
{
    private readonly IPage _page;
    public FixedDurationPricingPage(IPage page) { _page = page; }

    /// <summary>FixedDurationPricing: name = "fixedPrice" (line 295) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator FixedPrice => _page.Locator("[name='fixedPrice']");

    /// <summary>FixedDurationPricing: id = "fixedPrice" (line 312) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator FixedPrice2 => _page.Locator("#fixedPrice");

    /// <summary>FixedDurationPricing: placeholder = "e.g. 10" (line 357) — globally unique.</summary>
    public ILocator Eg10 => _page.Locator("[placeholder='e.g. 10']");

}