// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: FormBuilderPage
// File: (dynamicformbuilder)/FormBuilderPage.tsx
// Elements: 2 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>FormBuilderPage</c> component.</summary>
public sealed class FormBuilderPagePage
{
    private readonly IPage _page;
    public FormBuilderPagePage(IPage page) { _page = page; }

    /// <summary>FormBuilderPage: placeholder = "Type and select" (line 614) — globally unique.</summary>
    public ILocator TypeAndSelect => _page.Locator("[placeholder='Type and select']");

    /// <summary>FormBuilderPage: id = "formName" (line 764) — globally unique.</summary>
    public ILocator FormName => _page.Locator("#formName");

}