// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: GeneralSettings
// File: (permissionBuilder)/GeneralSettings.tsx
// Elements: 13 (deduped from 17 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>GeneralSettings</c> component.</summary>
public sealed class GeneralSettingsPage
{
    private readonly IPage _page;
    public GeneralSettingsPage(IPage page) { _page = page; }

    /// <summary>GeneralSettings: data-testid = "generalSettings-container" (line 868) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator GeneralSettingsContainer => _page.Locator("[data-testid='generalSettings-container']");

    /// <summary>GeneralSettings: name = "specialEvent" (line 881) — globally unique.</summary>
    public ILocator SpecialEvent => _page.Locator("[name='specialEvent']");

    /// <summary>GeneralSettings: name = "isScratchCardEnabled" (line 904) — globally unique.</summary>
    public ILocator IsScratchCardEnabled => _page.Locator("[name='isScratchCardEnabled']");

    /// <summary>GeneralSettings: placeholder = "Select" (line 932) — globally unique.</summary>
    public ILocator Select => _page.Locator("[placeholder='Select']");

    /// <summary>GeneralSettings: name = "isDaysSelectionEnabled" (line 948) — globally unique.</summary>
    public ILocator IsDaysSelectionEnabled => _page.Locator("[name='isDaysSelectionEnabled']");

    /// <summary>GeneralSettings: placeholder = "Select days" (line 978) — globally unique.</summary>
    public ILocator SelectDays => _page.Locator("[placeholder='Select days']");

    /// <summary>GeneralSettings: id = "startDateDelay" (line 999) — globally unique.</summary>
    public ILocator StartDateDelay => _page.Locator("#startDateDelay");

    /// <summary>GeneralSettings: placeholder = "Select Retention Period" (line 1081) — globally unique.</summary>
    public ILocator SelectRetentionPeriod => _page.Locator("[placeholder='Select Retention Period']");

    /// <summary>GeneralSettings: id = "retentionPeriod" (line 1085) — globally unique.</summary>
    public ILocator RetentionPeriod => _page.Locator("#retentionPeriod");

    /// <summary>GeneralSettings: id = "prefix" (line 1126) — globally unique.</summary>
    public ILocator Prefix => _page.Locator("#prefix");

    /// <summary>GeneralSettings: id = "displayDescription" (line 1174) — globally unique.</summary>
    public ILocator DisplayDescription => _page.Locator("#displayDescription");

    /// <summary>GeneralSettings: name = "permitMode" (line 1199) — globally unique.</summary>
    public ILocator PermitMode => _page.Locator("[name='permitMode']");

    /// <summary>GeneralSettings: id = "adminFeeForPermission" (line 1262) — globally unique.</summary>
    public ILocator AdminFeeForPermission => _page.Locator("#adminFeeForPermission");

}