// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: MerchantSettings
// File: (permissionBuilder)/MerchantSettings.tsx
// Elements: 13 (deduped from 22 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>MerchantSettings</c> component.</summary>
public sealed class MerchantSettingsPage
{
    private readonly IPage _page;
    public MerchantSettingsPage(IPage page) { _page = page; }

    /// <summary>MerchantSettings: data-testid = "merchantSettings-container" (line 262) — globally unique.</summary>
    public ILocator MerchantSettingsContainer => _page.Locator("[data-testid='merchantSettings-container']");

    /// <summary>MerchantSettings: id = "boMerchantId" (line 278) — globally unique.</summary>
    public ILocator BoMerchantId => _page.Locator("#boMerchantId");

    /// <summary>MerchantSettings: data-testid = "boMerchantIdTextField" (line 287) — globally unique.</summary>
    public ILocator BoMerchantIdTextField => _page.Locator("[data-testid='boMerchantIdTextField']");

    /// <summary>MerchantSettings: id = "boMerchantUser" (line 301) — globally unique.</summary>
    public ILocator BoMerchantUser => _page.Locator("#boMerchantUser");

    /// <summary>MerchantSettings: data-testid = "boMerchantUserTextField" (line 310) — globally unique.</summary>
    public ILocator BoMerchantUserTextField => _page.Locator("[data-testid='boMerchantUserTextField']");

    /// <summary>MerchantSettings: id = "boMerchantPassword" (line 324) — globally unique.</summary>
    public ILocator BoMerchantPassword => _page.Locator("#boMerchantPassword");

    /// <summary>MerchantSettings: data-testid = "boMerchantPasswordTextField" (line 337) — globally unique.</summary>
    public ILocator BoMerchantPasswordTextField => _page.Locator("[data-testid='boMerchantPasswordTextField']");

    /// <summary>MerchantSettings: id = "customerMerchantId" (line 353) — globally unique.</summary>
    public ILocator CustomerMerchantId => _page.Locator("#customerMerchantId");

    /// <summary>MerchantSettings: data-testid = "customerMerchantIdTextField" (line 364) — globally unique.</summary>
    public ILocator CustomerMerchantIdTextField => _page.Locator("[data-testid='customerMerchantIdTextField']");

    /// <summary>MerchantSettings: id = "customerMerchantUser" (line 377) — globally unique.</summary>
    public ILocator CustomerMerchantUser => _page.Locator("#customerMerchantUser");

    /// <summary>MerchantSettings: data-testid = "customerMerchantUserTextField" (line 385) — globally unique.</summary>
    public ILocator CustomerMerchantUserTextField => _page.Locator("[data-testid='customerMerchantUserTextField']");

    /// <summary>MerchantSettings: id = "customerMerchantPassword" (line 400) — globally unique.</summary>
    public ILocator CustomerMerchantPassword => _page.Locator("#customerMerchantPassword");

    /// <summary>MerchantSettings: data-testid = "customerMerchantPasswordTextField" (line 418) — globally unique.</summary>
    public ILocator CustomerMerchantPasswordTextField => _page.Locator("[data-testid='customerMerchantPasswordTextField']");

}