// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: MinIncrementalPricing
// File: (permissionBuilder)/MinIncrementalPricing.tsx
// Elements: 12 (deduped from 12 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>MinIncrementalPricing</c> component.</summary>
public sealed class MinIncrementalPricingPage
{
    private readonly IPage _page;
    public MinIncrementalPricingPage(IPage page) { _page = page; }

    /// <summary>MinIncrementalPricing: data-testid = "min-incremental-config" (line 504) — globally unique.</summary>
    public ILocator MinIncrementalConfig => _page.Locator("[data-testid='min-incremental-config']");

    /// <summary>MinIncrementalPricing: placeholder = "Optional" (line 561) — globally unique.</summary>
    public ILocator Optional => _page.Locator("[placeholder='Optional']");

    /// <summary>MinIncrementalPricing: name = "flatBayPrice" (line 629) — globally unique.</summary>
    public ILocator FlatBayPrice => _page.Locator("[name='flatBayPrice']");

    /// <summary>MinIncrementalPricing: id = "flat-hourly-rate" (line 666) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator FlatHourlyRate => _page.Locator("#flat-hourly-rate");

    /// <summary>MinIncrementalPricing: placeholder = "0.00" (line 673) — globally unique.</summary>
    public ILocator _000 => _page.Locator("[placeholder='0.00']");

    /// <summary>MinIncrementalPricing: data-testid = "flat-hourly-rate" (line 679) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator FlatHourlyRate2 => _page.Locator("[data-testid='flat-hourly-rate']");

    /// <summary>MinIncrementalPricing: id = "flat-daily-rate" (line 688) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator FlatDailyRate => _page.Locator("#flat-daily-rate");

    /// <summary>MinIncrementalPricing: data-testid = "flat-daily-rate" (line 700) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator FlatDailyRate2 => _page.Locator("[data-testid='flat-daily-rate']");

    /// <summary>MinIncrementalPricing: id = "flat-weekly-rate" (line 709) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator FlatWeeklyRate => _page.Locator("#flat-weekly-rate");

    /// <summary>MinIncrementalPricing: data-testid = "flat-weekly-rate" (line 721) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator FlatWeeklyRate2 => _page.Locator("[data-testid='flat-weekly-rate']");

    /// <summary>MinIncrementalPricing: id = "flat-monthly-rate" (line 730) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator FlatMonthlyRate => _page.Locator("#flat-monthly-rate");

    /// <summary>MinIncrementalPricing: data-testid = "flat-monthly-rate" (line 743) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator FlatMonthlyRate2 => _page.Locator("[data-testid='flat-monthly-rate']");

}