// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: page
// File: page.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>page</c> component.</summary>
public sealed class pagePage
{
    private readonly IPage _page;
    public pagePage(IPage page) { _page = page; }

    /// <summary>page: data-testid = "unsaved-dialog-close" (line 3266) — globally unique.</summary>
    public ILocator UnsavedDialogClose => _page.Locator("[data-testid='unsaved-dialog-close']");

}