// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: PaymentSettings
// File: (permissionBuilder)/PaymentSettings.tsx
// Elements: 3 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>PaymentSettings</c> component.</summary>
public sealed class PaymentSettingsPage
{
    private readonly IPage _page;
    public PaymentSettingsPage(IPage page) { _page = page; }

    /// <summary>PaymentSettings: data-testid = "paymentSettings-container" (line 203) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator PaymentSettingsContainer => _page.Locator("[data-testid='paymentSettings-container']");

    /// <summary>PaymentSettings: id = "paymentSettingsHelperText" (line 276) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator PaymentSettingsHelperText => _page.Locator("#paymentSettingsHelperText");

    /// <summary>PaymentSettings: placeholder = "Enter help description" (line 286) — globally unique.</summary>
    public ILocator EnterHelpDescription => _page.Locator("[placeholder='Enter help description']");

}