// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: PermissionLimit
// File: (permissionBuilder)/PermissionLimit.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>PermissionLimit</c> component.</summary>
public sealed class PermissionLimitPage
{
    private readonly IPage _page;
    public PermissionLimitPage(IPage page) { _page = page; }

    /// <summary>PermissionLimit: data-testid = "permissionLimits-container" (line 103) — globally unique.</summary>
    public ILocator PermissionLimitsContainer => _page.Locator("[data-testid='permissionLimits-container']");

    /// <summary>PermissionLimit: id = "limitCount" (line 147) — globally unique.</summary>
    public ILocator LimitCount => _page.Locator("#limitCount");

}