// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: PermissionBuilderForm
// File: (permissionBuilder)/PermissionBuilderForm.tsx
// Elements: 3 (deduped from 5 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>PermissionBuilderForm</c> component.</summary>
public sealed class PermissionBuilderFormPage
{
    private readonly IPage _page;
    public PermissionBuilderFormPage(IPage page) { _page = page; }

    /// <summary>PermissionBuilderForm: id = "permissionName" (line 329) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator PermissionName => _page.Locator("#permissionName");

    /// <summary>PermissionBuilderForm: placeholder = "Select" (line 366) — globally unique.</summary>
    public ILocator Select => _page.Locator("[placeholder='Select']");

    /// <summary>PermissionBuilderForm: id = "description" (line 416) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Description => _page.Locator("#description");

}