// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: PhysicalPermissionPrint
// File: (permissionBuilder)/PhysicalPermissionPrint.tsx
// Elements: 6 (deduped from 6 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>PhysicalPermissionPrint</c> component.</summary>
public sealed class PhysicalPermissionPrintPage
{
    private readonly IPage _page;
    public PhysicalPermissionPrintPage(IPage page) { _page = page; }

    /// <summary>PhysicalPermissionPrint: data-testid = "physicalPermitDocumentContainer" (line 789) — globally unique.</summary>
    public ILocator PhysicalPermitDocumentContainer => _page.Locator("[data-testid='physicalPermitDocumentContainer']");

    /// <summary>PhysicalPermissionPrint: id = "physicalDocumentEditorSearchField" (line 870) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator PhysicalDocumentEditorSearchField => _page.Locator("#physicalDocumentEditorSearchField");

    /// <summary>PhysicalPermissionPrint: placeholder = "Search" (line 876) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search']");

    /// <summary>PhysicalPermissionPrint: data-testid = "physicalPermitDocumentFileUploadDialog-close" (line 954) — globally unique.</summary>
    public ILocator PhysicalPermitDocumentFileUploadDialogClose => _page.Locator("[data-testid='physicalPermitDocumentFileUploadDialog-close']");

    /// <summary>PhysicalPermissionPrint: data-testid = "confimrationDialog-close" (line 1009) — globally unique.</summary>
    public ILocator ConfimrationDialogClose => _page.Locator("[data-testid='confimrationDialog-close']");

    /// <summary>PhysicalPermissionPrint: data-testid = "preview-close-icon" (line 1086) — globally unique.</summary>
    public ILocator PreviewCloseIcon => _page.Locator("[data-testid='preview-close-icon']");

}