// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: RefundSettings
// File: (permissionBuilder)/RefundSettings.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>RefundSettings</c> component.</summary>
public sealed class RefundSettingsPage
{
    private readonly IPage _page;
    public RefundSettingsPage(IPage page) { _page = page; }

    /// <summary>RefundSettings: data-testid = "refundSettings-container" (line 164) — globally unique.</summary>
    public ILocator RefundSettingsContainer => _page.Locator("[data-testid='refundSettings-container']");

    /// <summary>RefundSettings: id = "cancellationCharge" (line 229) — globally unique.</summary>
    public ILocator CancellationCharge => _page.Locator("#cancellationCharge");

}