// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: RenewalsAndReminders
// File: (permissionBuilder)/RenewalsAndReminders.tsx
// Elements: 5 (deduped from 5 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>RenewalsAndReminders</c> component.</summary>
public sealed class RenewalsAndRemindersPage
{
    private readonly IPage _page;
    public RenewalsAndRemindersPage(IPage page) { _page = page; }

    /// <summary>RenewalsAndReminders: placeholder = "Enter frequency" (line 1100) — globally unique.</summary>
    public ILocator EnterFrequency => _page.Locator("[placeholder='Enter frequency']");

    /// <summary>RenewalsAndReminders: placeholder = "Select period" (line 1169) — globally unique.</summary>
    public ILocator SelectPeriod => _page.Locator("[placeholder='Select period']");

    /// <summary>RenewalsAndReminders: id = "paper-frequency" (line 1241) — globally unique.</summary>
    public ILocator PaperFrequency => _page.Locator("#paper-frequency");

    /// <summary>RenewalsAndReminders: data-testid = "paper-period-autocomplete" (line 1313) — globally unique.</summary>
    public ILocator PaperPeriodAutocomplete => _page.Locator("[data-testid='paper-period-autocomplete']");

    /// <summary>RenewalsAndReminders: name = "renewal-radio" (line 1321) — globally unique.</summary>
    public ILocator RenewalRadio => _page.Locator("[name='renewal-radio']");

}