// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: SpecialEvents
// File: (permissionBuilder)/SpecialEvents.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>SpecialEvents</c> component.</summary>
public sealed class SpecialEventsPage
{
    private readonly IPage _page;
    public SpecialEventsPage(IPage page) { _page = page; }

    /// <summary>SpecialEvents: placeholder = "Select Days" (line 552) — globally unique.</summary>
    public ILocator SelectDays => _page.Locator("[placeholder='Select Days']");

    /// <summary>SpecialEvents: data-testid = "custom-autocomplete" (line 573) — globally unique.</summary>
    public ILocator CustomAutocomplete => _page.Locator("[data-testid='custom-autocomplete']");

}