// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: SpecialEventPropertiesMapping
// File: (permissionBuilder)/SpecialEventPropertiesMapping.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>SpecialEventPropertiesMapping</c> component.</summary>
public sealed class SpecialEventPropertiesMappingPage
{
    private readonly IPage _page;
    public SpecialEventPropertiesMappingPage(IPage page) { _page = page; }

    /// <summary>SpecialEventPropertiesMapping: placeholder = "Select Street" (line 177) — globally unique.</summary>
    public ILocator SelectStreet => _page.Locator("[placeholder='Select Street']");

}