// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: StandardPricing
// File: (permissionBuilder)/StandardPricing.tsx
// Elements: 11 (deduped from 11 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>StandardPricing</c> component.</summary>
public sealed class StandardPricingPage
{
    private readonly IPage _page;
    public StandardPricingPage(IPage page) { _page = page; }

    /// <summary>StandardPricing: data-testid = "standard-pricing-config" (line 412) — globally unique.</summary>
    public ILocator StandardPricingConfig => _page.Locator("[data-testid='standard-pricing-config']");

    /// <summary>StandardPricing: name = "standardFlatBayPrice" (line 455) — globally unique.</summary>
    public ILocator StandardFlatBayPrice => _page.Locator("[name='standardFlatBayPrice']");

    /// <summary>StandardPricing: id = "standard-flat-hourly-rate" (line 496) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator StandardFlatHourlyRate => _page.Locator("#standard-flat-hourly-rate");

    /// <summary>StandardPricing: placeholder = "0.00" (line 503) — globally unique.</summary>
    public ILocator _000 => _page.Locator("[placeholder='0.00']");

    /// <summary>StandardPricing: data-testid = "standard-flat-hourly-rate" (line 508) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator StandardFlatHourlyRate2 => _page.Locator("[data-testid='standard-flat-hourly-rate']");

    /// <summary>StandardPricing: id = "standard-flat-daily-rate" (line 517) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator StandardFlatDailyRate => _page.Locator("#standard-flat-daily-rate");

    /// <summary>StandardPricing: data-testid = "standard-flat-daily-rate" (line 530) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator StandardFlatDailyRate2 => _page.Locator("[data-testid='standard-flat-daily-rate']");

    /// <summary>StandardPricing: id = "standard-flat-weekly-rate" (line 538) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator StandardFlatWeeklyRate => _page.Locator("#standard-flat-weekly-rate");

    /// <summary>StandardPricing: data-testid = "standard-flat-weekly-rate" (line 551) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator StandardFlatWeeklyRate2 => _page.Locator("[data-testid='standard-flat-weekly-rate']");

    /// <summary>StandardPricing: id = "standard-flat-monthly-rate" (line 560) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator StandardFlatMonthlyRate => _page.Locator("#standard-flat-monthly-rate");

    /// <summary>StandardPricing: data-testid = "standard-flat-monthly-rate" (line 573) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator StandardFlatMonthlyRate2 => _page.Locator("[data-testid='standard-flat-monthly-rate']");

}