// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: SuspensionSettings
// File: (permissionBuilder)/SuspensionSettings.tsx
// Elements: 8 (deduped from 8 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>SuspensionSettings</c> component.</summary>
public sealed class SuspensionSettingsPage
{
    private readonly IPage _page;
    public SuspensionSettingsPage(IPage page) { _page = page; }

    /// <summary>SuspensionSettings: data-testid = "suspensionSettings-container" (line 489) — globally unique.</summary>
    public ILocator SuspensionSettingsContainer => _page.Locator("[data-testid='suspensionSettings-container']");

    /// <summary>SuspensionSettings: name = "shortNotice" (line 500) — globally unique.</summary>
    public ILocator ShortNotice => _page.Locator("[name='shortNotice']");

    /// <summary>SuspensionSettings: id = "shortNoticeLeadTimeFrequency" (line 512) — globally unique.</summary>
    public ILocator ShortNoticeLeadTimeFrequency => _page.Locator("#shortNoticeLeadTimeFrequency");

    /// <summary>SuspensionSettings: placeholder = "0" (line 516) — globally unique.</summary>
    public ILocator _0 => _page.Locator("[placeholder='0']");

    /// <summary>SuspensionSettings: id = "shortNoticeSuspensionFee" (line 550) — globally unique.</summary>
    public ILocator ShortNoticeSuspensionFee => _page.Locator("#shortNoticeSuspensionFee");

    /// <summary>SuspensionSettings: placeholder = "Enter suspension fee" (line 556) — globally unique.</summary>
    public ILocator EnterSuspensionFee => _page.Locator("[placeholder='Enter suspension fee']");

    /// <summary>SuspensionSettings: name = "extendSuspension" (line 586) — globally unique.</summary>
    public ILocator ExtendSuspension => _page.Locator("[name='extendSuspension']");

    /// <summary>SuspensionSettings: name = "multipleBaySelection" (line 613) — globally unique.</summary>
    public ILocator MultipleBaySelection => _page.Locator("[name='multipleBaySelection']");

}