// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: TemplateSettings
// File: (permissionBuilder)/TemplateSettings.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>TemplateSettings</c> component.</summary>
public sealed class TemplateSettingsPage
{
    private readonly IPage _page;
    public TemplateSettingsPage(IPage page) { _page = page; }

    /// <summary>TemplateSettings: data-testid = "templateSettings-container" (line 37) — globally unique.</summary>
    public ILocator TemplateSettingsContainer => _page.Locator("[data-testid='templateSettings-container']");

}