// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: VehicleSettings
// File: (permissionBuilder)/VehicleSettings.tsx
// Elements: 10 (deduped from 13 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>VehicleSettings</c> component.</summary>
public sealed class VehicleSettingsPage
{
    private readonly IPage _page;
    public VehicleSettingsPage(IPage page) { _page = page; }

    /// <summary>VehicleSettings: data-testid = "vehicleSettings-container" (line 420) — globally unique.</summary>
    public ILocator VehicleSettingsContainer => _page.Locator("[data-testid='vehicleSettings-container']");

    /// <summary>VehicleSettings: id = "numberPlateChangeLimit" (line 430) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator NumberPlateChangeLimit => _page.Locator("#numberPlateChangeLimit");

    /// <summary>VehicleSettings: data-testid = "numberPlateChangeLimit" (line 434) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator NumberPlateChangeLimit2 => _page.Locator("[data-testid='numberPlateChangeLimit']");

    /// <summary>VehicleSettings: placeholder = "Select" (line 478) — globally unique.</summary>
    public ILocator Select => _page.Locator("[placeholder='Select']");

    /// <summary>VehicleSettings: id = "score" (line 487) — globally unique.</summary>
    public ILocator Score => _page.Locator("#score");

    /// <summary>VehicleSettings: name = "multipleVehiclesAllowed" (line 536) — globally unique.</summary>
    public ILocator MultipleVehiclesAllowed => _page.Locator("[name='multipleVehiclesAllowed']");

    /// <summary>VehicleSettings: data-testid = "allowedVehicleCount" (line 561) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator AllowedVehicleCount => _page.Locator("[data-testid='allowedVehicleCount']");

    /// <summary>VehicleSettings: id = "numberOfSeats" (line 681) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator NumberOfSeats => _page.Locator("#numberOfSeats");

    /// <summary>VehicleSettings: data-testid = "numberOfSeats" (line 689) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator NumberOfSeats2 => _page.Locator("[data-testid='numberOfSeats']");

    /// <summary>VehicleSettings: data-testid = "euroStandard" (line 792) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator EuroStandard => _page.Locator("[data-testid='euroStandard']");

}