// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: VisitorPortalSettings
// File: (permissionBuilder)/VisitorPortalSettings.tsx
// Elements: 8 (deduped from 9 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>VisitorPortalSettings</c> component.</summary>
public sealed class VisitorPortalSettingsPage
{
    private readonly IPage _page;
    public VisitorPortalSettingsPage(IPage page) { _page = page; }

    /// <summary>VisitorPortalSettings: data-testid = "visitor-portal-settings-container" (line 165) — globally unique.</summary>
    public ILocator VisitorPortalSettingsContainer => _page.Locator("[data-testid='visitor-portal-settings-container']");

    /// <summary>VisitorPortalSettings: name = "vrnOnly" (line 174) — globally unique.</summary>
    public ILocator VrnOnly => _page.Locator("[name='vrnOnly']");

    /// <summary>VisitorPortalSettings: id = "visitorPortalLinkExpirationDays" (line 190) — globally unique.</summary>
    public ILocator VisitorPortalLinkExpirationDays => _page.Locator("#visitorPortalLinkExpirationDays");

    /// <summary>VisitorPortalSettings: name = "allowBackDates" (line 203) — globally unique.</summary>
    public ILocator AllowBackDates => _page.Locator("[name='allowBackDates']");

    /// <summary>VisitorPortalSettings: id = "backDaysLimit" (line 218) — globally unique.</summary>
    public ILocator BackDaysLimit => _page.Locator("#backDaysLimit");

    /// <summary>VisitorPortalSettings: name = "startSessionEOD" (line 243) — globally unique.</summary>
    public ILocator StartSessionEOD => _page.Locator("[name='startSessionEOD']");

    /// <summary>VisitorPortalSettings: name = "endSessionEOD" (line 254) — globally unique.</summary>
    public ILocator EndSessionEOD => _page.Locator("[name='endSessionEOD']");

    /// <summary>VisitorPortalSettings: name = "isPriceByBookEnabled" (line 265) — globally unique.</summary>
    public ILocator IsPriceByBookEnabled => _page.Locator("[name='isPriceByBookEnabled']");

}