// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: WhiteMailReminderEditor
// File: (permissionBuilder)/WhiteMailReminderEditor.tsx
// Elements: 4 (deduped from 5 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>WhiteMailReminderEditor</c> component.</summary>
public sealed class WhiteMailReminderEditorPage
{
    private readonly IPage _page;
    public WhiteMailReminderEditorPage(IPage page) { _page = page; }

    /// <summary>WhiteMailReminderEditor: data-testid = "whiteMailReminderEditorContainer" (line 342) — globally unique.</summary>
    public ILocator WhiteMailReminderEditorContainer => _page.Locator("[data-testid='whiteMailReminderEditorContainer']");

    /// <summary>WhiteMailReminderEditor: placeholder = "Select Reminder Type" (line 355) — globally unique.</summary>
    public ILocator SelectReminderType => _page.Locator("[placeholder='Select Reminder Type']");

    /// <summary>WhiteMailReminderEditor: data-testid = "whiteMailReminderSelect" (line 375) — globally unique.</summary>
    public ILocator WhiteMailReminderSelect => _page.Locator("[data-testid='whiteMailReminderSelect']");

    /// <summary>WhiteMailReminderEditor: id = "physicalDocumentEditorSearchField" (line 396) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator PhysicalDocumentEditorSearchField => _page.Locator("#physicalDocumentEditorSearchField");

}