// <auto-generated />
// Generated from inventory: inventory-builder.json
// Source component: ZoneMapping
// File: (permissionBuilder)/ZoneMapping.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Builder;

/// <summary>Page object for the <c>ZoneMapping</c> component.</summary>
public sealed class ZoneMappingPage
{
    private readonly IPage _page;
    public ZoneMappingPage(IPage page) { _page = page; }

    /// <summary>ZoneMapping: data-testid = "zoneMapping-container" (line 393) — globally unique.</summary>
    public ILocator ZoneMappingContainer => _page.Locator("[data-testid='zoneMapping-container']");

}