// <auto-generated />
// Generated from inventory: inventory-systemaudits.json
// Source component: SystemAuditListPage
// File: SystemAuditListPage.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Systemaudits;

/// <summary>Page object for the <c>SystemAuditListPage</c> component.</summary>
public sealed class SystemAuditListPagePage
{
    private readonly IPage _page;
    public SystemAuditListPagePage(IPage page) { _page = page; }

    /// <summary>SystemAuditListPage: h-text = "System Audits" (line 516) — globally unique.</summary>
    public ILocator SystemAudits => _page.Locator("[data-testid='System Audits']");

}