// <auto-generated />
// Generated from inventory: inventory-whitemailremainder.json
// Source component: WhiteMailReminderList
// File: WhiteMailReminderList.tsx
// Elements: 3 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Whitemailremainder;

/// <summary>Page object for the <c>WhiteMailReminderList</c> component.</summary>
public sealed class WhiteMailReminderListPage
{
    private readonly IPage _page;
    public WhiteMailReminderListPage(IPage page) { _page = page; }

    /// <summary>WhiteMailReminderList: placeholder = "Search by Reference Number, Applicant Name" (line 488) — globally unique.</summary>
    public ILocator SearchByReferenceNumberApplicantName => _page.Locator("[placeholder='Search by Reference Number, Applicant Name']");

    /// <summary>WhiteMailReminderList: aria-label = "Clear" (line 493) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>WhiteMailReminderList: placeholder = "Search…" (line 613) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

}