// <auto-generated />
// Generated from inventory: inventory-dashboard.json
// Source component: page
// File: page.tsx
// Elements: 1 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Dashboard;

/// <summary>Page object for the <c>page</c> component.</summary>
public sealed class pagePage
{
    private readonly IPage _page;
    public pagePage(IPage page) { _page = page; }

    /// <summary>page: tab-text = "APPLICATIONS" (line 24) — globally unique.</summary>
    public ILocator APPLICATIONS => _page.Locator("[data-testid='APPLICATIONS']");

}