// <auto-generated />
// Generated from inventory: inventory-suspensions.json
// Source component: CeoTaskHistory
// File: CeoTask/CeoTaskHistory.tsx
// Elements: 3 (deduped from 4 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Suspensions;

/// <summary>Page object for the <c>CeoTaskHistory</c> component.</summary>
public sealed class CeoTaskHistoryPage
{
    private readonly IPage _page;
    public CeoTaskHistoryPage(IPage page) { _page = page; }

    /// <summary>CeoTaskHistory: h-text = "CEO Completion Evidence" (line 156) — globally unique.</summary>
    public ILocator CEOCompletionEvidence => _page.Locator("[data-testid='CEO Completion Evidence']");

    /// <summary>CeoTaskHistory: aria-label = "Close" (line 160) — globally unique.</summary>
    public ILocator Close => _page.Locator("[aria-label='Close']");

    /// <summary>CeoTaskHistory: h-text = "CEO Task History" (line 558) — globally unique.</summary>
    public ILocator CEOTaskHistory => _page.Locator("[data-testid='CEO Task History']");

}