// <auto-generated />
// Generated from inventory: inventory-emails.json
// Source component: TemplatesEmailsList
// File: TemplatesEmailsList.tsx
// Elements: 3 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Emails;

/// <summary>Page object for the <c>TemplatesEmailsList</c> component.</summary>
public sealed class TemplatesEmailsListPage
{
    private readonly IPage _page;
    public TemplatesEmailsListPage(IPage page) { _page = page; }

    /// <summary>TemplatesEmailsList: placeholder = "Search by Template Name, Permission Type" (line 113) — globally unique.</summary>
    public ILocator SearchByTemplateNamePermissionType => _page.Locator("[placeholder='Search by Template Name, Permission Type']");

    /// <summary>TemplatesEmailsList: aria-label = "Clear" (line 120) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>TemplatesEmailsList: placeholder = "Search…" (line 205) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

}