// <auto-generated />
// Generated from inventory: inventory-pricing.json
// Source component: NonZonalList
// File: NonZonalList.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Pricing;

/// <summary>Page object for the <c>NonZonalList</c> component.</summary>
public sealed class NonZonalListPage
{
    private readonly IPage _page;
    public NonZonalListPage(IPage page) { _page = page; }

    /// <summary>NonZonalList: placeholder = "Search…" (line 393) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

}