// <auto-generated />
// Generated from inventory: inventory-pricing.json
// Source component: PricingDetailScreen
// File: PricingDetailScreen.tsx
// Elements: 19 (deduped from 21 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Pricing;

/// <summary>Page object for the <c>PricingDetailScreen</c> component.</summary>
public sealed class PricingDetailScreenPage
{
    private readonly IPage _page;
    public PricingDetailScreenPage(IPage page) { _page = page; }

    /// <summary>PricingDetailScreen: id = "pricing-text" (line 1687) — globally unique.</summary>
    public ILocator PricingText => _page.Locator("#pricing-text");

    /// <summary>PricingDetailScreen: data-testid = "pricingTextInput" (line 1704) — globally unique.</summary>
    public ILocator PricingTextInput => _page.Locator("[data-testid='pricingTextInput']");

    /// <summary>PricingDetailScreen: placeholder = "Select Permission Type" (line 1740) — globally unique.</summary>
    public ILocator SelectPermissionType => _page.Locator("[placeholder='Select Permission Type']");

    /// <summary>PricingDetailScreen: placeholder = "Select Sub Type" (line 1783) — globally unique.</summary>
    public ILocator SelectSubType => _page.Locator("[placeholder='Select Sub Type']");

    /// <summary>PricingDetailScreen: id = "duration-frequency" (line 2585) — globally unique.</summary>
    public ILocator DurationFrequency => _page.Locator("#duration-frequency");

    /// <summary>PricingDetailScreen: data-testid = "durationFrequencyInput" (line 2606) — globally unique.</summary>
    public ILocator DurationFrequencyInput => _page.Locator("[data-testid='durationFrequencyInput']");

    /// <summary>PricingDetailScreen: placeholder = "Select period" (line 2629) — globally unique.</summary>
    public ILocator SelectPeriod => _page.Locator("[placeholder='Select period']");

    /// <summary>PricingDetailScreen: data-testid = "Duplicate" (line 2678) — globally unique.</summary>
    public ILocator Duplicate => _page.Locator("[data-testid='Duplicate']");

    /// <summary>PricingDetailScreen: data-testid = "Remove" (line 2691) — globally unique.</summary>
    public ILocator Remove => _page.Locator("[data-testid='Remove']");

    /// <summary>PricingDetailScreen: placeholder = "Enter no of voucher(s) per book" (line 2756) — globally unique.</summary>
    public ILocator EnterNoOfVouchersPerBook => _page.Locator("[placeholder='Enter no of voucher(s) per book']");

    /// <summary>PricingDetailScreen: placeholder = "Enter band price" (line 2784) — globally unique.</summary>
    public ILocator EnterBandPrice => _page.Locator("[placeholder='Enter band price']");

    /// <summary>PricingDetailScreen: placeholder = "Enter diesel surcharge" (line 2844) — globally unique.</summary>
    public ILocator EnterDieselSurcharge => _page.Locator("[placeholder='Enter diesel surcharge']");

    /// <summary>PricingDetailScreen: id = "no-of-pages-per-book" (line 2896) — globally unique.</summary>
    public ILocator NoOfPagesPerBook => _page.Locator("#no-of-pages-per-book");

    /// <summary>PricingDetailScreen: placeholder = "Enter number of voucher(s) per book" (line 2918) — globally unique.</summary>
    public ILocator EnterNumberOfVouchersPerBook => _page.Locator("[placeholder='Enter number of voucher(s) per book']");

    /// <summary>PricingDetailScreen: data-testid = "noOfPagesPerBookInput" (line 2922) — globally unique.</summary>
    public ILocator NoOfPagesPerBookInput => _page.Locator("[data-testid='noOfPagesPerBookInput']");

    /// <summary>PricingDetailScreen: id = "band-price" (line 2930) — globally unique.</summary>
    public ILocator BandPrice => _page.Locator("#band-price");

    /// <summary>PricingDetailScreen: data-testid = "bandPriceInput" (line 2965) — globally unique.</summary>
    public ILocator BandPriceInput => _page.Locator("[data-testid='bandPriceInput']");

    /// <summary>PricingDetailScreen: id = "diesel-surcharge" (line 2977) — globally unique.</summary>
    public ILocator DieselSurcharge => _page.Locator("#diesel-surcharge");

    /// <summary>PricingDetailScreen: data-testid = "dieselSurchargeInput" (line 3006) — globally unique.</summary>
    public ILocator DieselSurchargeInput => _page.Locator("[data-testid='dieselSurchargeInput']");

}