// <auto-generated />
// Generated from inventory: inventory-pricing.json
// Source component: RuleBasedNonZonalList
// File: RuleBasedNonZonalList.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Pricing;

/// <summary>Page object for the <c>RuleBasedNonZonalList</c> component.</summary>
public sealed class RuleBasedNonZonalListPage
{
    private readonly IPage _page;
    public RuleBasedNonZonalListPage(IPage page) { _page = page; }

    /// <summary>RuleBasedNonZonalList: placeholder = "Search…" (line 396) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

}