// <auto-generated />
// Generated from inventory: inventory-pricing.json
// Source component: ZonalList
// File: ZonalList.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Pricing;

/// <summary>Page object for the <c>ZonalList</c> component.</summary>
public sealed class ZonalListPage
{
    private readonly IPage _page;
    public ZonalListPage(IPage page) { _page = page; }

    /// <summary>ZonalList: placeholder = "Search…" (line 439) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

}