// <auto-generated />
// Generated from inventory: inventory-groups.json
// Source component: GroupList
// File: GroupList.tsx
// Elements: 3 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Groups;

/// <summary>Page object for the <c>GroupList</c> component.</summary>
public sealed class GroupListPage
{
    private readonly IPage _page;
    public GroupListPage(IPage page) { _page = page; }

    /// <summary>GroupList: placeholder = "Search by Group Name" (line 129) — globally unique.</summary>
    public ILocator SearchByGroupName => _page.Locator("[placeholder='Search by Group Name']");

    /// <summary>GroupList: aria-label = "Clear" (line 137) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>GroupList: placeholder = "Search…" (line 145) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

}