// <auto-generated />
// Generated from inventory: inventory-groups.json
// Source component: PermissionGroupForm
// File: (permissionGroup)/PermissionGroupForm.tsx
// Elements: 6 (deduped from 9 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Groups;

/// <summary>Page object for the <c>PermissionGroupForm</c> component.</summary>
public sealed class PermissionGroupFormPage
{
    private readonly IPage _page;
    public PermissionGroupFormPage(IPage page) { _page = page; }

    /// <summary>PermissionGroupForm: id = "groupName" (line 362) — globally unique.</summary>
    public ILocator GroupName => _page.Locator("#groupName");

    /// <summary>PermissionGroupForm: placeholder = "Select" (line 395) — globally unique.</summary>
    public ILocator Select => _page.Locator("[placeholder='Select']");

    /// <summary>PermissionGroupForm: id = "houseHoldLimit" (line 419) — globally unique.</summary>
    public ILocator HouseHoldLimit => _page.Locator("#houseHoldLimit");

    /// <summary>PermissionGroupForm: id = "maximumNumberPerGroup" (line 493) — globally unique.</summary>
    public ILocator MaximumNumberPerGroup => _page.Locator("#maximumNumberPerGroup");

    /// <summary>PermissionGroupForm: name = "exampleRadio" (line 545) — globally unique.</summary>
    public ILocator ExampleRadio => _page.Locator("[name='exampleRadio']");

    /// <summary>PermissionGroupForm: data-testid = "mwlswitch" (line 575) — globally unique.</summary>
    public ILocator Mwlswitch => _page.Locator("[data-testid='mwlswitch']");

}