// <auto-generated />
// Generated from inventory: inventory-exploreapplications.json
// Source component: Explore
// File: Explore.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Exploreapplications;

/// <summary>Page object for the <c>Explore</c> component.</summary>
public sealed class ExplorePage
{
    private readonly IPage _page;
    public ExplorePage(IPage page) { _page = page; }

    /// <summary>Explore: placeholder = "Search" (line 385) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search']");

    /// <summary>Explore: menuitem-text = "All" (line 405) — globally unique.</summary>
    public ILocator All => _page.Locator("[data-testid='All']");

}