// <auto-generated />
// Generated from inventory: inventory-purchasereason.json
// Source component: AddEditPurchaseReason
// File: AddEditPurchaseReason.tsx
// Elements: 12 (deduped from 12 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Purchasereason;

/// <summary>Page object for the <c>AddEditPurchaseReason</c> component.</summary>
public sealed class AddEditPurchaseReasonPage
{
    private readonly IPage _page;
    public AddEditPurchaseReasonPage(IPage page) { _page = page; }

    /// <summary>AddEditPurchaseReason: aria-label = "Remove field" (line 165) — globally unique.</summary>
    public ILocator RemoveField => _page.Locator("[aria-label='Remove field']");

    /// <summary>AddEditPurchaseReason: placeholder = "e.g. License Number" (line 176) — globally unique.</summary>
    public ILocator EgLicenseNumber => _page.Locator("[placeholder='e.g. License Number']");

    /// <summary>AddEditPurchaseReason: placeholder = "e.g. Enter license number" (line 224) — globally unique.</summary>
    public ILocator EgEnterLicenseNumber => _page.Locator("[placeholder='e.g. Enter license number']");

    /// <summary>AddEditPurchaseReason: placeholder = "e.g. Enter weight in kg" (line 235) — globally unique.</summary>
    public ILocator EgEnterWeightInKg => _page.Locator("[placeholder='e.g. Enter weight in kg']");

    /// <summary>AddEditPurchaseReason: placeholder = "0" (line 249) — globally unique.</summary>
    public ILocator _0 => _page.Locator("[placeholder='0']");

    /// <summary>AddEditPurchaseReason: placeholder = "9999" (line 262) — globally unique.</summary>
    public ILocator _9999 => _page.Locator("[placeholder='9999']");

    /// <summary>AddEditPurchaseReason: aria-label = "Remove option" (line 293) — globally unique.</summary>
    public ILocator RemoveOption => _page.Locator("[aria-label='Remove option']");

    /// <summary>AddEditPurchaseReason: h-text = "Overview" (line 365) — globally unique.</summary>
    public ILocator Overview => _page.Locator("[data-testid='Overview']");

    /// <summary>AddEditPurchaseReason: aria-label = "Edit" (line 371) — globally unique.</summary>
    public ILocator Edit => _page.Locator("[aria-label='Edit']");

    /// <summary>AddEditPurchaseReason: id = "pr-name-input" (line 700) — globally unique.</summary>
    public ILocator PrNameInput => _page.Locator("#pr-name-input");

    /// <summary>AddEditPurchaseReason: placeholder = "Enter purchase reason" (line 707) — globally unique.</summary>
    public ILocator EnterPurchaseReason => _page.Locator("[placeholder='Enter purchase reason']");

    /// <summary>AddEditPurchaseReason: h-text = "Additional Fields" (line 754) — globally unique.</summary>
    public ILocator AdditionalFields => _page.Locator("[data-testid='Additional Fields']");

}