// <auto-generated />
// Generated from inventory: inventory-purchasereason.json
// Source component: page
// File: page.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Purchasereason;

/// <summary>Page object for the <c>page</c> component.</summary>
public sealed class pagePage
{
    private readonly IPage _page;
    public pagePage(IPage page) { _page = page; }

    /// <summary>page: h-text = "Purchase Reasons" (line 221) — globally unique.</summary>
    public ILocator PurchaseReasons => _page.Locator("[data-testid='Purchase Reasons']");

}