// <auto-generated />
// Generated from inventory: inventory-purchasereason.json
// Source component: PurchaseReasonList
// File: PurchaseReasonList.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Purchasereason;

/// <summary>Page object for the <c>PurchaseReasonList</c> component.</summary>
public sealed class PurchaseReasonListPage
{
    private readonly IPage _page;
    public PurchaseReasonListPage(IPage page) { _page = page; }

    /// <summary>PurchaseReasonList: aria-label = "Delete" (line 338) — globally unique.</summary>
    public ILocator Delete => _page.Locator("[aria-label='Delete']");

}