// <auto-generated />
// Generated from inventory: inventory-myworkitems.json
// Source component: AssignedGrid
// File: AssignedGrid.tsx
// Elements: 3 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Myworkitems;

/// <summary>Page object for the <c>AssignedGrid</c> component.</summary>
public sealed class AssignedGridPage
{
    private readonly IPage _page;
    public AssignedGridPage(IPage page) { _page = page; }

    /// <summary>AssignedGrid: placeholder = "Search…" (line 104) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>AssignedGrid: aria-label = "Clear" (line 109) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>AssignedGrid: h-text = "Re Assign Work Items" (line 620) — globally unique.</summary>
    public ILocator ReAssignWorkItems => _page.Locator("[data-testid='Re Assign Work Items']");

}