// <auto-generated />
// Generated from inventory: inventory-myworkitems.json
// Source component: UnassignedGrid
// File: UnassignedGrid.tsx
// Elements: 3 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Myworkitems;

/// <summary>Page object for the <c>UnassignedGrid</c> component.</summary>
public sealed class UnassignedGridPage
{
    private readonly IPage _page;
    public UnassignedGridPage(IPage page) { _page = page; }

    /// <summary>UnassignedGrid: placeholder = "Search…" (line 103) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>UnassignedGrid: aria-label = "Clear" (line 107) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>UnassignedGrid: h-text = "Assign Work Items" (line 534) — globally unique.</summary>
    public ILocator AssignWorkItems => _page.Locator("[data-testid='Assign Work Items']");

}