// <auto-generated />
// Generated from inventory: inventory-myworkitems.json
// Source component: WaitingListGrid
// File: WaitingListGrid.tsx
// Elements: 7 (deduped from 7 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Myworkitems;

/// <summary>Page object for the <c>WaitingListGrid</c> component.</summary>
public sealed class WaitingListGridPage
{
    private readonly IPage _page;
    public WaitingListGridPage(IPage page) { _page = page; }

    /// <summary>WaitingListGrid: data-testid = "WaitingListGrid-gridData" (line 538) — globally unique.</summary>
    public ILocator WaitingListGridGridData => _page.Locator("[data-testid='WaitingListGrid-gridData']");

    /// <summary>WaitingListGrid: id = "current-active-panel" (line 587) — globally unique.</summary>
    public ILocator CurrentActivePanel => _page.Locator("#current-active-panel");

    /// <summary>WaitingListGrid: placeholder = "Search…" (line 628) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>WaitingListGrid: aria-label = "Clear" (line 644) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>WaitingListGrid: data-testid = "DeleteIcon" (line 718) — globally unique.</summary>
    public ILocator DeleteIcon => _page.Locator("[data-testid='DeleteIcon']");

    /// <summary>WaitingListGrid: data-testid = "CloseIcon" (line 737) — globally unique.</summary>
    public ILocator CloseIcon => _page.Locator("[data-testid='CloseIcon']");

    /// <summary>WaitingListGrid: data-testid = "waitingListGrid-container" (line 769) — globally unique.</summary>
    public ILocator WaitingListGridContainer => _page.Locator("[data-testid='waitingListGrid-container']");

}