// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: AddAddressAssign
// File: AddAddressAssign/AddAddressAssign.tsx
// Elements: 11 (deduped from 12 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>AddAddressAssign</c> component.</summary>
public sealed class AddAddressAssignPage
{
    private readonly IPage _page;
    public AddAddressAssignPage(IPage page) { _page = page; }

    /// <summary>AddAddressAssign: id = "search" (line 209) — WARNING: value reused 5x — scope to parent if needed.</summary>
    public ILocator Search => _page.Locator("#search");

    /// <summary>AddAddressAssign: h-text = "Given Address" (line 497) — globally unique.</summary>
    public ILocator GivenAddress => _page.Locator("[data-testid='Given Address']");

    /// <summary>AddAddressAssign: h-text = "Map Address" (line 523) — globally unique.</summary>
    public ILocator MapAddress => _page.Locator("[data-testid='Map Address']");

    /// <summary>AddAddressAssign: placeholder = "Select zone" (line 543) — globally unique.</summary>
    public ILocator SelectZone => _page.Locator("[placeholder='Select zone']");

    /// <summary>AddAddressAssign: id = "postcode" (line 551) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Postcode => _page.Locator("#postcode");

    /// <summary>AddAddressAssign: id = "property" (line 563) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Property => _page.Locator("#property");

    /// <summary>AddAddressAssign: id = "street" (line 573) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Street => _page.Locator("#street");

    /// <summary>AddAddressAssign: id = "uprn" (line 584) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Uprn => _page.Locator("#uprn");

    /// <summary>AddAddressAssign: id = "usrn" (line 591) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Usrn => _page.Locator("#usrn");

    /// <summary>AddAddressAssign: placeholder = "Select town" (line 615) — globally unique.</summary>
    public ILocator SelectTown => _page.Locator("[placeholder='Select town']");

    /// <summary>AddAddressAssign: id = "subject" (line 630) — WARNING: value reused 3x — scope to parent if needed.</summary>
    public ILocator Subject => _page.Locator("#subject");

}