// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: ApplicationPaymentHistory
// File: ApplicationPaymentHistory/ApplicationPaymentHistory.tsx
// Elements: 5 (deduped from 8 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>ApplicationPaymentHistory</c> component.</summary>
public sealed class ApplicationPaymentHistoryPage
{
    private readonly IPage _page;
    public ApplicationPaymentHistoryPage(IPage page) { _page = page; }

    /// <summary>ApplicationPaymentHistory: data-testid = "mwl-date-time-picker" (line 857) — globally unique.</summary>
    public ILocator MwlDateTimePicker => _page.Locator("[data-testid='mwl-date-time-picker']");

    /// <summary>ApplicationPaymentHistory: id = "amountPaid" (line 867) — globally unique.</summary>
    public ILocator AmountPaid => _page.Locator("#amountPaid");

    /// <summary>ApplicationPaymentHistory: id = "paymentReference" (line 888) — globally unique.</summary>
    public ILocator PaymentReference => _page.Locator("#paymentReference");

    /// <summary>ApplicationPaymentHistory: id = "invoiceNumber" (line 907) — globally unique.</summary>
    public ILocator InvoiceNumber => _page.Locator("#invoiceNumber");

    /// <summary>ApplicationPaymentHistory: data-testid = "vehicle-logo" (line 981) — WARNING: value reused 7x — scope to parent if needed.</summary>
    public ILocator VehicleLogo => _page.Locator("[data-testid='vehicle-logo']");

}