// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: ApplicationApplicant
// File: ApplicationApplicant/ApplicationApplicant.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>ApplicationApplicant</c> component.</summary>
public sealed class ApplicationApplicantPage
{
    private readonly IPage _page;
    public ApplicationApplicantPage(IPage page) { _page = page; }

    /// <summary>ApplicationApplicant: data-testid = "header-content" (line 199) — globally unique.</summary>
    public ILocator HeaderContent => _page.Locator("[data-testid='header-content']");

}