// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: ApplicationActionSendEmail
// File: ApplicationActionSendEmail/ApplicationActionSendEmail.tsx
// Elements: 27 (deduped from 34 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>ApplicationActionSendEmail</c> component.</summary>
public sealed class ApplicationActionSendEmailPage
{
    private readonly IPage _page;
    public ApplicationActionSendEmailPage(IPage page) { _page = page; }

    /// <summary>ApplicationActionSendEmail: id = "search" (line 2550) — WARNING: value reused 5x — scope to parent if needed.</summary>
    public ILocator Search => _page.Locator("#search");

    /// <summary>ApplicationActionSendEmail: placeholder = "Select cancellation reason" (line 2904) — globally unique.</summary>
    public ILocator SelectCancellationReason => _page.Locator("[placeholder='Select cancellation reason']");

    /// <summary>ApplicationActionSendEmail: id = "otherReason" (line 2926) — globally unique.</summary>
    public ILocator OtherReason => _page.Locator("#otherReason");

    /// <summary>ApplicationActionSendEmail: placeholder = "Select rejection reason" (line 2974) — globally unique.</summary>
    public ILocator SelectRejectionReason => _page.Locator("[placeholder='Select rejection reason']");

    /// <summary>ApplicationActionSendEmail: id = "otherRejectionReason" (line 2994) — globally unique.</summary>
    public ILocator OtherRejectionReason => _page.Locator("#otherRejectionReason");

    /// <summary>ApplicationActionSendEmail: id = "suspendReason" (line 3018) — globally unique.</summary>
    public ILocator SuspendReason => _page.Locator("#suspendReason");

    /// <summary>ApplicationActionSendEmail: placeholder = "Select suspend reason" (line 3041) — globally unique.</summary>
    public ILocator SelectSuspendReason => _page.Locator("[placeholder='Select suspend reason']");

    /// <summary>ApplicationActionSendEmail: id = "otherSuspendReason" (line 3059) — globally unique.</summary>
    public ILocator OtherSuspendReason => _page.Locator("#otherSuspendReason");

    /// <summary>ApplicationActionSendEmail: placeholder = "Select on-hold reason" (line 3100) — globally unique.</summary>
    public ILocator SelectOnHoldReason => _page.Locator("[placeholder='Select on-hold reason']");

    /// <summary>ApplicationActionSendEmail: id = "otherOnHoldReason" (line 3139) — globally unique.</summary>
    public ILocator OtherOnHoldReason => _page.Locator("#otherOnHoldReason");

    /// <summary>ApplicationActionSendEmail: placeholder = "Select" (line 3163) — globally unique.</summary>
    public ILocator Select => _page.Locator("[placeholder='Select']");

    /// <summary>ApplicationActionSendEmail: placeholder = "Select zone" (line 3202) — globally unique.</summary>
    public ILocator SelectZone => _page.Locator("[placeholder='Select zone']");

    /// <summary>ApplicationActionSendEmail: id = "discount" (line 3403) — globally unique.</summary>
    public ILocator Discount => _page.Locator("#discount");

    /// <summary>ApplicationActionSendEmail: placeholder = "Select postcode" (line 3464) — globally unique.</summary>
    public ILocator SelectPostcode => _page.Locator("[placeholder='Select postcode']");

    /// <summary>ApplicationActionSendEmail: placeholder = "Select property" (line 3502) — globally unique.</summary>
    public ILocator SelectProperty => _page.Locator("[placeholder='Select property']");

    /// <summary>ApplicationActionSendEmail: placeholder = "Select street" (line 3542) — globally unique.</summary>
    public ILocator SelectStreet => _page.Locator("[placeholder='Select street']");

    /// <summary>ApplicationActionSendEmail: id = "townDetails" (line 3558) — globally unique.</summary>
    public ILocator TownDetails => _page.Locator("#townDetails");

    /// <summary>ApplicationActionSendEmail: h-text = "Given Address" (line 3938) — globally unique.</summary>
    public ILocator GivenAddress => _page.Locator("[data-testid='Given Address']");

    /// <summary>ApplicationActionSendEmail: h-text = "Map Address" (line 3972) — globally unique.</summary>
    public ILocator MapAddress => _page.Locator("[data-testid='Map Address']");

    /// <summary>ApplicationActionSendEmail: id = "postcode" (line 4002) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Postcode => _page.Locator("#postcode");

    /// <summary>ApplicationActionSendEmail: id = "property" (line 4019) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Property => _page.Locator("#property");

    /// <summary>ApplicationActionSendEmail: id = "street" (line 4031) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Street => _page.Locator("#street");

    /// <summary>ApplicationActionSendEmail: id = "uprn" (line 4044) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Uprn => _page.Locator("#uprn");

    /// <summary>ApplicationActionSendEmail: id = "usrn" (line 4054) — WARNING: value reused 2x — scope to parent if needed.</summary>
    public ILocator Usrn => _page.Locator("#usrn");

    /// <summary>ApplicationActionSendEmail: placeholder = "Select town" (line 4072) — globally unique.</summary>
    public ILocator SelectTown => _page.Locator("[placeholder='Select town']");

    /// <summary>ApplicationActionSendEmail: id = "subject" (line 4094) — WARNING: value reused 3x — scope to parent if needed.</summary>
    public ILocator Subject => _page.Locator("#subject");

    /// <summary>ApplicationActionSendEmail: data-testid = "vehicle-logo" (line 4169) — WARNING: value reused 7x — scope to parent if needed.</summary>
    public ILocator VehicleLogo => _page.Locator("[data-testid='vehicle-logo']");

}