// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: ApplicationVehicle
// File: ApplicationVehicle/ApplicationVehicle.tsx
// Elements: 12 (deduped from 16 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>ApplicationVehicle</c> component.</summary>
public sealed class ApplicationVehiclePage
{
    private readonly IPage _page;
    public ApplicationVehiclePage(IPage page) { _page = page; }

    /// <summary>ApplicationVehicle: data-testid = "DeleteIcon" (line 801) — globally unique.</summary>
    public ILocator DeleteIcon => _page.Locator("[data-testid='DeleteIcon']");

    /// <summary>ApplicationVehicle: placeholder = "Search…" (line 975) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>ApplicationVehicle: aria-label = "Clear" (line 990) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>ApplicationVehicle: data-testid = "suspension-vrm-container" (line 998) — globally unique.</summary>
    public ILocator SuspensionVrmContainer => _page.Locator("[data-testid='suspension-vrm-container']");

    /// <summary>ApplicationVehicle: data-testid = "addIcon" (line 1013) — globally unique.</summary>
    public ILocator AddIcon => _page.Locator("[data-testid='addIcon']");

    /// <summary>ApplicationVehicle: data-testid = "suspension-vrm-info" (line 1019) — globally unique.</summary>
    public ILocator SuspensionVrmInfo => _page.Locator("[data-testid='suspension-vrm-info']");

    /// <summary>ApplicationVehicle: data-testid = "suspension-vrm-empty" (line 1157) — globally unique.</summary>
    public ILocator SuspensionVrmEmpty => _page.Locator("[data-testid='suspension-vrm-empty']");

    /// <summary>ApplicationVehicle: id = "vrm-drawer-input" (line 1192) — globally unique.</summary>
    public ILocator VrmDrawerInput => _page.Locator("#vrm-drawer-input");

    /// <summary>ApplicationVehicle: role = "button" (line 1252) — globally unique.</summary>
    public ILocator Button => _page.Locator("[role='button']");

    /// <summary>ApplicationVehicle: data-testid = "star-icon" (line 1272) — globally unique.</summary>
    public ILocator StarIcon => _page.Locator("[data-testid='star-icon']");

    /// <summary>ApplicationVehicle: id = "search" (line 1438) — WARNING: value reused 5x — scope to parent if needed.</summary>
    public ILocator Search2 => _page.Locator("#search");

    /// <summary>ApplicationVehicle: data-testid = "vehicle-logo" (line 1461) — WARNING: value reused 7x — scope to parent if needed.</summary>
    public ILocator VehicleLogo => _page.Locator("[data-testid='vehicle-logo']");

}