// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: ApplicationOverView
// File: ApplicationOverView/ApplicationOverView.tsx
// Elements: 3 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>ApplicationOverView</c> component.</summary>
public sealed class ApplicationOverViewPage
{
    private readonly IPage _page;
    public ApplicationOverViewPage(IPage page) { _page = page; }

    /// <summary>ApplicationOverView: placeholder = "Enter serial number" (line 1332) — globally unique.</summary>
    public ILocator EnterSerialNumber => _page.Locator("[placeholder='Enter serial number']");

    /// <summary>ApplicationOverView: data-testid = "mwl-date-time-picker-start" (line 1707) — globally unique.</summary>
    public ILocator MwlDateTimePickerStart => _page.Locator("[data-testid='mwl-date-time-picker-start']");

    /// <summary>ApplicationOverView: data-testid = "mwl-date-time-picker-end" (line 1793) — globally unique.</summary>
    public ILocator MwlDateTimePickerEnd => _page.Locator("[data-testid='mwl-date-time-picker-end']");

}