// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: ApplicationSendEmail
// File: ApplicationEmailList/ApplicationSendEmail/ApplicationSendEmail.tsx
// Elements: 5 (deduped from 8 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>ApplicationSendEmail</c> component.</summary>
public sealed class ApplicationSendEmailPage
{
    private readonly IPage _page;
    public ApplicationSendEmailPage(IPage page) { _page = page; }

    /// <summary>ApplicationSendEmail: id = "search" (line 648) — WARNING: value reused 5x — scope to parent if needed.</summary>
    public ILocator Search => _page.Locator("#search");

    /// <summary>ApplicationSendEmail: id = "receiverEmail" (line 691) — globally unique.</summary>
    public ILocator ReceiverEmail => _page.Locator("#receiverEmail");

    /// <summary>ApplicationSendEmail: placeholder = "Select" (line 732) — globally unique.</summary>
    public ILocator Select => _page.Locator("[placeholder='Select']");

    /// <summary>ApplicationSendEmail: id = "subject" (line 769) — WARNING: value reused 3x — scope to parent if needed.</summary>
    public ILocator Subject => _page.Locator("#subject");

    /// <summary>ApplicationSendEmail: data-testid = "vehicle-logo" (line 815) — WARNING: value reused 7x — scope to parent if needed.</summary>
    public ILocator VehicleLogo => _page.Locator("[data-testid='vehicle-logo']");

}