// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: ApplicationApplicantFpnTable
// File: ApplicationApplicant/ApplicationApplicantFpnTable.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>ApplicationApplicantFpnTable</c> component.</summary>
public sealed class ApplicationApplicantFpnTablePage
{
    private readonly IPage _page;
    public ApplicationApplicantFpnTablePage(IPage page) { _page = page; }

    /// <summary>ApplicationApplicantFpnTable: data-testid = "fpn-table" (line 486) — globally unique.</summary>
    public ILocator FpnTable => _page.Locator("[data-testid='fpn-table']");

}