// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: ApplicationAuditLog
// File: ApplicationAuditLog/ApplicationAuditLog.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>ApplicationAuditLog</c> component.</summary>
public sealed class ApplicationAuditLogPage
{
    private readonly IPage _page;
    public ApplicationAuditLogPage(IPage page) { _page = page; }

    /// <summary>ApplicationAuditLog: placeholder = "Search…" (line 94) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>ApplicationAuditLog: aria-label = "Clear" (line 98) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

}