// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: ApplicationEmailList
// File: ApplicationEmailList/ApplicationEmailList.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>ApplicationEmailList</c> component.</summary>
public sealed class ApplicationEmailListPage
{
    private readonly IPage _page;
    public ApplicationEmailListPage(IPage page) { _page = page; }

    /// <summary>ApplicationEmailList: role = "button" (line 105) — globally unique.</summary>
    public ILocator Button => _page.Locator("[role='button']");

}