// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: ApplicationVehicleEdit
// File: ApplicationVehicle/ApplicationVehicleEdit.tsx
// Elements: 8 (deduped from 9 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>ApplicationVehicleEdit</c> component.</summary>
public sealed class ApplicationVehicleEditPage
{
    private readonly IPage _page;
    public ApplicationVehicleEditPage(IPage page) { _page = page; }

    /// <summary>ApplicationVehicleEdit: id = "registrationNumber" (line 468) — globally unique.</summary>
    public ILocator RegistrationNumber => _page.Locator("#registrationNumber");

    /// <summary>ApplicationVehicleEdit: placeholder = "Select vehicle category" (line 588) — globally unique.</summary>
    public ILocator SelectVehicleCategory => _page.Locator("[placeholder='Select vehicle category']");

    /// <summary>ApplicationVehicleEdit: placeholder = "Select make" (line 616) — globally unique.</summary>
    public ILocator SelectMake => _page.Locator("[placeholder='Select make']");

    /// <summary>ApplicationVehicleEdit: placeholder = "Select model" (line 643) — globally unique.</summary>
    public ILocator SelectModel => _page.Locator("[placeholder='Select model']");

    /// <summary>ApplicationVehicleEdit: placeholder = "Select color" (line 671) — globally unique.</summary>
    public ILocator SelectColor => _page.Locator("[placeholder='Select color']");

    /// <summary>ApplicationVehicleEdit: placeholder = "Select fuel type" (line 698) — globally unique.</summary>
    public ILocator SelectFuelType => _page.Locator("[placeholder='Select fuel type']");

    /// <summary>ApplicationVehicleEdit: placeholder = "Select CO2 emission" (line 725) — globally unique.</summary>
    public ILocator SelectCO2Emission => _page.Locator("[placeholder='Select CO2 emission']");

    /// <summary>ApplicationVehicleEdit: aria-label = "Remove file" (line 822) — globally unique.</summary>
    public ILocator RemoveFile => _page.Locator("[aria-label='Remove file']");

}