// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: AssignTaskToCEO
// File: AssignTaskToCEO/AssignTaskToCEO.tsx
// Elements: 7 (deduped from 7 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>AssignTaskToCEO</c> component.</summary>
public sealed class AssignTaskToCEOPage
{
    private readonly IPage _page;
    public AssignTaskToCEOPage(IPage page) { _page = page; }

    /// <summary>AssignTaskToCEO: id = "assignTaskTitle" (line 97) — globally unique.</summary>
    public ILocator AssignTaskTitle => _page.Locator("#assignTaskTitle");

    /// <summary>AssignTaskToCEO: placeholder = "Title" (line 106) — globally unique.</summary>
    public ILocator Title => _page.Locator("[placeholder='Title']");

    /// <summary>AssignTaskToCEO: id = "assignTaskCategory" (line 111) — globally unique.</summary>
    public ILocator AssignTaskCategory => _page.Locator("#assignTaskCategory");

    /// <summary>AssignTaskToCEO: placeholder = "Category" (line 121) — globally unique.</summary>
    public ILocator Category => _page.Locator("[placeholder='Category']");

    /// <summary>AssignTaskToCEO: id = "assignTaskLocation" (line 125) — globally unique.</summary>
    public ILocator AssignTaskLocation => _page.Locator("#assignTaskLocation");

    /// <summary>AssignTaskToCEO: placeholder = "Location" (line 136) — globally unique.</summary>
    public ILocator Location => _page.Locator("[placeholder='Location']");

    /// <summary>AssignTaskToCEO: id = "assignTaskComments" (line 140) — globally unique.</summary>
    public ILocator AssignTaskComments => _page.Locator("#assignTaskComments");

}