// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: ExtendDurationSlider
// File: ExtendDurationSlider.tsx
// Elements: 1 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>ExtendDurationSlider</c> component.</summary>
public sealed class ExtendDurationSliderPage
{
    private readonly IPage _page;
    public ExtendDurationSliderPage(IPage page) { _page = page; }

    /// <summary>ExtendDurationSlider: id = "current-postpone-date" (line 110) — globally unique.</summary>
    public ILocator CurrentPostponeDate => _page.Locator("#current-postpone-date");

}