// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: page
// File: page.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>page</c> component.</summary>
public sealed class pagePage
{
    private readonly IPage _page;
    public pagePage(IPage page) { _page = page; }

    /// <summary>page: data-testid = "ExpandLessIcon" (line 313) — globally unique.</summary>
    public ILocator ExpandLessIcon => _page.Locator("[data-testid='ExpandLessIcon']");

}