// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: PermissionsDetailsList
// File: PermissionsDetailsList.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>PermissionsDetailsList</c> component.</summary>
public sealed class PermissionsDetailsListPage
{
    private readonly IPage _page;
    public PermissionsDetailsListPage(IPage page) { _page = page; }

    /// <summary>PermissionsDetailsList: aria-label = "Clear" (line 301) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>PermissionsDetailsList: placeholder = "Searchâ€¦" (line 468) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Searchâ€¦']");

}