// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: RenewalDocumentUpload
// File: RenewalDocumentUpload/RenewalDocumentUpload.tsx
// Elements: 3 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>RenewalDocumentUpload</c> component.</summary>
public sealed class RenewalDocumentUploadPage
{
    private readonly IPage _page;
    public RenewalDocumentUploadPage(IPage page) { _page = page; }

    /// <summary>RenewalDocumentUpload: h-text = "Upload required document for renew" (line 645) — globally unique.</summary>
    public ILocator UploadRequiredDocumentForRenew => _page.Locator("[data-testid='Upload required document for renew']");

    /// <summary>RenewalDocumentUpload: data-testid = "vehicle-logo" (line 725) — WARNING: value reused 7x — scope to parent if needed.</summary>
    public ILocator VehicleLogo => _page.Locator("[data-testid='vehicle-logo']");

    /// <summary>RenewalDocumentUpload: aria-label = "Remove file" (line 782) — globally unique.</summary>
    public ILocator RemoveFile => _page.Locator("[aria-label='Remove file']");

}