// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: RenewalSummary
// File: RenewalSummary/RenewalSummary.tsx
// Elements: 3 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>RenewalSummary</c> component.</summary>
public sealed class RenewalSummaryPage
{
    private readonly IPage _page;
    public RenewalSummaryPage(IPage page) { _page = page; }

    /// <summary>RenewalSummary: h-text = "Overview" (line 114) — globally unique.</summary>
    public ILocator Overview => _page.Locator("[data-testid='Overview']");

    /// <summary>RenewalSummary: h-text = "Documents" (line 138) — globally unique.</summary>
    public ILocator Documents => _page.Locator("[data-testid='Documents']");

    /// <summary>RenewalSummary: h-text = "Pricing" (line 165) — globally unique.</summary>
    public ILocator Pricing => _page.Locator("[data-testid='Pricing']");

}