// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: VisitorVoucherPermit
// File: VoucherPermit/VisitorVoucherPermit.tsx
// Elements: 15 (deduped from 15 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>VisitorVoucherPermit</c> component.</summary>
public sealed class VisitorVoucherPermitPage
{
    private readonly IPage _page;
    public VisitorVoucherPermitPage(IPage page) { _page = page; }

    /// <summary>VisitorVoucherPermit: h-text = "Send Visitor Voucher" (line 907) — globally unique.</summary>
    public ILocator SendVisitorVoucher => _page.Locator("[data-testid='Send Visitor Voucher']");

    /// <summary>VisitorVoucherPermit: id = "send-voucher-quantity" (line 938) — globally unique.</summary>
    public ILocator SendVoucherQuantity => _page.Locator("#send-voucher-quantity");

    /// <summary>VisitorVoucherPermit: id = "send-voucher-id" (line 960) — globally unique.</summary>
    public ILocator SendVoucherId => _page.Locator("#send-voucher-id");

    /// <summary>VisitorVoucherPermit: id = "send-email" (line 972) — globally unique.</summary>
    public ILocator SendEmail => _page.Locator("#send-email");

    /// <summary>VisitorVoucherPermit: placeholder = "sample@email.com" (line 981) — globally unique.</summary>
    public ILocator Sampleemailcom => _page.Locator("[placeholder='sample@email.com']");

    /// <summary>VisitorVoucherPermit: id = "send-confirm-email" (line 989) — globally unique.</summary>
    public ILocator SendConfirmEmail => _page.Locator("#send-confirm-email");

    /// <summary>VisitorVoucherPermit: h-text = "Visitor Voucher Activation" (line 1028) — globally unique.</summary>
    public ILocator VisitorVoucherActivation => _page.Locator("[data-testid='Visitor Voucher Activation']");

    /// <summary>VisitorVoucherPermit: id = "activate-voucher-quantity" (line 1085) — globally unique.</summary>
    public ILocator ActivateVoucherQuantity => _page.Locator("#activate-voucher-quantity");

    /// <summary>VisitorVoucherPermit: id = "activate-voucher-id" (line 1122) — globally unique.</summary>
    public ILocator ActivateVoucherId => _page.Locator("#activate-voucher-id");

    /// <summary>VisitorVoucherPermit: placeholder = "Select Vehicle" (line 1251) — globally unique.</summary>
    public ILocator SelectVehicle => _page.Locator("[placeholder='Select Vehicle']");

    /// <summary>VisitorVoucherPermit: name = "activationType" (line 1264) — globally unique.</summary>
    public ILocator ActivationType => _page.Locator("[name='activationType']");

    /// <summary>VisitorVoucherPermit: data-testid = "activate-voucher-start-datetime" (line 1298) — globally unique.</summary>
    public ILocator ActivateVoucherStartDatetime => _page.Locator("[data-testid='activate-voucher-start-datetime']");

    /// <summary>VisitorVoucherPermit: name = "favoriteVehicle" (line 1309) — globally unique.</summary>
    public ILocator FavoriteVehicle => _page.Locator("[name='favoriteVehicle']");

    /// <summary>VisitorVoucherPermit: id = "activate-vehicle-nickname" (line 1331) — globally unique.</summary>
    public ILocator ActivateVehicleNickname => _page.Locator("#activate-vehicle-nickname");

    /// <summary>VisitorVoucherPermit: h-text = "Non-enforceable hours overlapping" (line 1392) — globally unique.</summary>
    public ILocator NonEnforceableHoursOverlapping => _page.Locator("[data-testid='Non-enforceable hours overlapping']");

}