// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: VoucherPermitOverView
// File: VoucherPermit/VoucherPermitOverView.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>VoucherPermitOverView</c> component.</summary>
public sealed class VoucherPermitOverViewPage
{
    private readonly IPage _page;
    public VoucherPermitOverViewPage(IPage page) { _page = page; }

    /// <summary>VoucherPermitOverView: role = "button" (line 137) — globally unique.</summary>
    public ILocator Button => _page.Locator("[role='button']");

}