// <auto-generated />
// Generated from inventory: inventory-applications.json
// Source component: VoucherPermitHistory
// File: VoucherPermit/VoucherPermitHistory.tsx
// Elements: 3 (deduped from 4 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Applications;

/// <summary>Page object for the <c>VoucherPermitHistory</c> component.</summary>
public sealed class VoucherPermitHistoryPage
{
    private readonly IPage _page;
    public VoucherPermitHistoryPage(IPage page) { _page = page; }

    /// <summary>VoucherPermitHistory: h-text = "Voucher History" (line 279) — globally unique.</summary>
    public ILocator VoucherHistory => _page.Locator("[data-testid='Voucher History']");

    /// <summary>VoucherPermitHistory: id = "search" (line 289) — WARNING: value reused 5x — scope to parent if needed.</summary>
    public ILocator Search => _page.Locator("#search");

    /// <summary>VoucherPermitHistory: menuitem-text = "All" (line 316) — globally unique.</summary>
    public ILocator All => _page.Locator("[data-testid='All']");

}