// <auto-generated />
// Generated from inventory: inventory-termsandcondition.json
// Source component: CreateTemplate
// File: (termsAndConditionBuilder)/CreateTemplate.tsx
// Elements: 4 (deduped from 5 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Termsandcondition;

/// <summary>Page object for the <c>CreateTemplate</c> component.</summary>
public sealed class CreateTemplatePage
{
    private readonly IPage _page;
    public CreateTemplatePage(IPage page) { _page = page; }

    /// <summary>CreateTemplate: id = "templateName" (line 194) — globally unique.</summary>
    public ILocator TemplateName => _page.Locator("#templateName");

    /// <summary>CreateTemplate: data-testid = "templateNameInput" (line 200) — globally unique.</summary>
    public ILocator TemplateNameInput => _page.Locator("[data-testid='templateNameInput']");

    /// <summary>CreateTemplate: placeholder = "Select Permission Type" (line 220) — globally unique.</summary>
    public ILocator SelectPermissionType => _page.Locator("[placeholder='Select Permission Type']");

    /// <summary>CreateTemplate: data-testid = "permissionTypeIdAutoComplete" (line 225) — globally unique.</summary>
    public ILocator PermissionTypeIdAutoComplete => _page.Locator("[data-testid='permissionTypeIdAutoComplete']");

}