// <auto-generated />
// Generated from inventory: inventory-termsandcondition.json
// Source component: TermsAndConditionList
// File: TermsAndConditionList.tsx
// Elements: 1 (deduped from 1 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Termsandcondition;

/// <summary>Page object for the <c>TermsAndConditionList</c> component.</summary>
public sealed class TermsAndConditionListPage
{
    private readonly IPage _page;
    public TermsAndConditionListPage(IPage page) { _page = page; }

    /// <summary>TermsAndConditionList: placeholder = "Search…" (line 266) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

}