// <auto-generated />
// Generated from inventory: inventory-zones.json
// Source component: AddZone
// File: AddZone.tsx
// Elements: 8 (deduped from 8 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Zones;

/// <summary>Page object for the <c>AddZone</c> component.</summary>
public sealed class AddZonePage
{
    private readonly IPage _page;
    public AddZonePage(IPage page) { _page = page; }

    /// <summary>AddZone: data-testid = "addAndEditLocation-gridData" (line 388) — globally unique.</summary>
    public ILocator AddAndEditLocationGridData => _page.Locator("[data-testid='addAndEditLocation-gridData']");

    /// <summary>AddZone: id = "current-active-panel" (line 555) — globally unique.</summary>
    public ILocator CurrentActivePanel => _page.Locator("#current-active-panel");

    /// <summary>AddZone: placeholder = "Search…" (line 593) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>AddZone: data-testid = "DeleteIcon" (line 727) — globally unique.</summary>
    public ILocator DeleteIcon => _page.Locator("[data-testid='DeleteIcon']");

    /// <summary>AddZone: data-testid = "CloseIcon" (line 746) — globally unique.</summary>
    public ILocator CloseIcon => _page.Locator("[data-testid='CloseIcon']");

    /// <summary>AddZone: id = "zoneName" (line 1341) — globally unique.</summary>
    public ILocator ZoneName => _page.Locator("#zoneName");

    /// <summary>AddZone: placeholder = "Type and select" (line 1362) — globally unique.</summary>
    public ILocator TypeAndSelect => _page.Locator("[placeholder='Type and select']");

    /// <summary>AddZone: name = "backOfficeUse" (line 1371) — globally unique.</summary>
    public ILocator BackOfficeUse => _page.Locator("[name='backOfficeUse']");

}