// <auto-generated />
// Generated from inventory: inventory-zones.json
// Source component: EditZonePermission
// File: (permissions)/EditZonePermission.tsx
// Elements: 5 (deduped from 6 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Zones;

/// <summary>Page object for the <c>EditZonePermission</c> component.</summary>
public sealed class EditZonePermissionPage
{
    private readonly IPage _page;
    public EditZonePermissionPage(IPage page) { _page = page; }

    /// <summary>EditZonePermission: id = "zone" (line 364) — globally unique.</summary>
    public ILocator Zone => _page.Locator("#zone");

    /// <summary>EditZonePermission: id = "userZone" (line 419) — globally unique.</summary>
    public ILocator UserZone => _page.Locator("#userZone");

    /// <summary>EditZonePermission: id = "household" (line 474) — globally unique.</summary>
    public ILocator Household => _page.Locator("#household");

    /// <summary>EditZonePermission: id = "voucher" (line 529) — globally unique.</summary>
    public ILocator Voucher => _page.Locator("#voucher");

    /// <summary>EditZonePermission: id = "blueBadge" (line 583) — globally unique.</summary>
    public ILocator BlueBadge => _page.Locator("#blueBadge");

}