// <auto-generated />
// Generated from inventory: inventory-zones.json
// Source component: StreetsList
// File: (streetslist)/StreetsList.tsx
// Elements: 2 (deduped from 2 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Zones;

/// <summary>Page object for the <c>StreetsList</c> component.</summary>
public sealed class StreetsListPage
{
    private readonly IPage _page;
    public StreetsListPage(IPage page) { _page = page; }

    /// <summary>StreetsList: placeholder = "Search…" (line 83) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

    /// <summary>StreetsList: aria-label = "Clear" (line 87) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

}