// <auto-generated />
// Generated from inventory: inventory-zones.json
// Source component: ZonesList
// File: ZonesList.tsx
// Elements: 3 (deduped from 3 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Zones;

/// <summary>Page object for the <c>ZonesList</c> component.</summary>
public sealed class ZonesListPage
{
    private readonly IPage _page;
    public ZonesListPage(IPage page) { _page = page; }

    /// <summary>ZonesList: placeholder = "Search by Zone Name" (line 137) — globally unique.</summary>
    public ILocator SearchByZoneName => _page.Locator("[placeholder='Search by Zone Name']");

    /// <summary>ZonesList: aria-label = "Clear" (line 144) — globally unique.</summary>
    public ILocator Clear => _page.Locator("[aria-label='Clear']");

    /// <summary>ZonesList: placeholder = "Search…" (line 228) — globally unique.</summary>
    public ILocator Search => _page.Locator("[placeholder='Search…']");

}