// <auto-generated />
// Generated from inventory: inventory-contractsettings.json
// Source component: ContractSettings
// File: ContractSettings.tsx
// Elements: 68 (deduped from 71 raw matches)
// DO NOT EDIT BY HAND — re-run pom-generator.js after UI changes.

using Microsoft.Playwright;

namespace MNPS.WorkFlow.WebPages.Generated.Contractsettings;

/// <summary>Page object for the <c>ContractSettings</c> component.</summary>
public sealed class ContractSettingsPage
{
    private readonly IPage _page;
    public ContractSettingsPage(IPage page) { _page = page; }

    /// <summary>ContractSettings: h-text = "Contract Settings" (line 3195) — globally unique.</summary>
    public ILocator ContractSettings => _page.Locator("[data-testid='Contract Settings']");

    /// <summary>ContractSettings: id = "customer-settings" (line 3238) — globally unique.</summary>
    public ILocator CustomerSettings => _page.Locator("#customer-settings");

    /// <summary>ContractSettings: id = "isBlueBadge" (line 3252) — globally unique.</summary>
    public ILocator IsBlueBadge => _page.Locator("#isBlueBadge");

    /// <summary>ContractSettings: id = "blueBadgeLimit" (line 3290) — globally unique.</summary>
    public ILocator BlueBadgeLimit => _page.Locator("#blueBadgeLimit");

    /// <summary>ContractSettings: id = "isDOBMandatoryApplicant" (line 3307) — globally unique.</summary>
    public ILocator IsDOBMandatoryApplicant => _page.Locator("#isDOBMandatoryApplicant");

    /// <summary>ContractSettings: id = "isUsersAutoActivate" (line 3332) — globally unique.</summary>
    public ILocator IsUsersAutoActivate => _page.Locator("#isUsersAutoActivate");

    /// <summary>ContractSettings: id = "visitor-permit" (line 3353) — globally unique.</summary>
    public ILocator VisitorPermit => _page.Locator("#visitor-permit");

    /// <summary>ContractSettings: id = "minimumNumberOfVisitorVouchers" (line 3370) — globally unique.</summary>
    public ILocator MinimumNumberOfVisitorVouchers => _page.Locator("#minimumNumberOfVisitorVouchers");

    /// <summary>ContractSettings: id = "maximumNumberOfVisitorVouchers" (line 3391) — globally unique.</summary>
    public ILocator MaximumNumberOfVisitorVouchers => _page.Locator("#maximumNumberOfVisitorVouchers");

    /// <summary>ContractSettings: id = "minimumNumberOfScratchCardBooks" (line 3410) — globally unique.</summary>
    public ILocator MinimumNumberOfScratchCardBooks => _page.Locator("#minimumNumberOfScratchCardBooks");

    /// <summary>ContractSettings: id = "maximumNumberOfScratchCardBooks" (line 3434) — globally unique.</summary>
    public ILocator MaximumNumberOfScratchCardBooks => _page.Locator("#maximumNumberOfScratchCardBooks");

    /// <summary>ContractSettings: id = "fees" (line 3444) — globally unique.</summary>
    public ILocator Fees => _page.Locator("#fees");

    /// <summary>ContractSettings: id = "adminFee" (line 3463) — globally unique.</summary>
    public ILocator AdminFee => _page.Locator("#adminFee");

    /// <summary>ContractSettings: id = "temporary-vehicle" (line 3483) — globally unique.</summary>
    public ILocator TemporaryVehicle => _page.Locator("#temporary-vehicle");

    /// <summary>ContractSettings: id = "temporaryVehicleValidityFrequency" (line 3505) — globally unique.</summary>
    public ILocator TemporaryVehicleValidityFrequency => _page.Locator("#temporaryVehicleValidityFrequency");

    /// <summary>ContractSettings: placeholder = "Select Period" (line 3530) — globally unique.</summary>
    public ILocator SelectPeriod => _page.Locator("[placeholder='Select Period']");

    /// <summary>ContractSettings: id = "temporaryVehicleAddLimitFrequency" (line 3578) — globally unique.</summary>
    public ILocator TemporaryVehicleAddLimitFrequency => _page.Locator("#temporaryVehicleAddLimitFrequency");

    /// <summary>ContractSettings: id = "numberOfTemporarySwitches" (line 3666) — globally unique.</summary>
    public ILocator NumberOfTemporarySwitches => _page.Locator("#numberOfTemporarySwitches");

    /// <summary>ContractSettings: id = "documents-expiration" (line 3676) — globally unique.</summary>
    public ILocator DocumentsExpiration => _page.Locator("#documents-expiration");

    /// <summary>ContractSettings: id = "expirationDurationFrequency" (line 3698) — globally unique.</summary>
    public ILocator ExpirationDurationFrequency => _page.Locator("#expirationDurationFrequency");

    /// <summary>ContractSettings: data-testid = "expirationDurationPeriodId" (line 3730) — globally unique.</summary>
    public ILocator ExpirationDurationPeriodId => _page.Locator("[data-testid='expirationDurationPeriodId']");

    /// <summary>ContractSettings: id = "fields-for-vehicles" (line 3738) — globally unique.</summary>
    public ILocator FieldsForVehicles => _page.Locator("#fields-for-vehicles");

    /// <summary>ContractSettings: id = "isVehicleTypeEnabled" (line 3754) — globally unique.</summary>
    public ILocator IsVehicleTypeEnabled => _page.Locator("#isVehicleTypeEnabled");

    /// <summary>ContractSettings: id = "isFuelTypeEnabled" (line 3783) — globally unique.</summary>
    public ILocator IsFuelTypeEnabled => _page.Locator("#isFuelTypeEnabled");

    /// <summary>ContractSettings: id = "isVehicleMakeEnabled" (line 3813) — globally unique.</summary>
    public ILocator IsVehicleMakeEnabled => _page.Locator("#isVehicleMakeEnabled");

    /// <summary>ContractSettings: id = "isVehicleModelEnabled" (line 3842) — globally unique.</summary>
    public ILocator IsVehicleModelEnabled => _page.Locator("#isVehicleModelEnabled");

    /// <summary>ContractSettings: id = "isVehicleColorEnabled" (line 3872) — globally unique.</summary>
    public ILocator IsVehicleColorEnabled => _page.Locator("#isVehicleColorEnabled");

    /// <summary>ContractSettings: id = "isCo2EmissionEnabled" (line 3902) — globally unique.</summary>
    public ILocator IsCo2EmissionEnabled => _page.Locator("#isCo2EmissionEnabled");

    /// <summary>ContractSettings: id = "isEuroStandardEnabled" (line 3932) — globally unique.</summary>
    public ILocator IsEuroStandardEnabled => _page.Locator("#isEuroStandardEnabled");

    /// <summary>ContractSettings: id = "isEngineSizeEnabled" (line 3961) — globally unique.</summary>
    public ILocator IsEngineSizeEnabled => _page.Locator("#isEngineSizeEnabled");

    /// <summary>ContractSettings: id = "isNumberPlateTaxBandEnabled" (line 3993) — globally unique.</summary>
    public ILocator IsNumberPlateTaxBandEnabled => _page.Locator("#isNumberPlateTaxBandEnabled");

    /// <summary>ContractSettings: id = "isNumberOfSeatsEnabled" (line 4016) — globally unique.</summary>
    public ILocator IsNumberOfSeatsEnabled => _page.Locator("#isNumberOfSeatsEnabled");

    /// <summary>ContractSettings: id = "isFirstDateOfRegistration" (line 4038) — globally unique.</summary>
    public ILocator IsFirstDateOfRegistration => _page.Locator("#isFirstDateOfRegistration");

    /// <summary>ContractSettings: id = "permission-closure" (line 4053) — globally unique.</summary>
    public ILocator PermissionClosure => _page.Locator("#permission-closure");

    /// <summary>ContractSettings: id = "paymentFailureGracePeriodFrequency" (line 4078) — globally unique.</summary>
    public ILocator PaymentFailureGracePeriodFrequency => _page.Locator("#paymentFailureGracePeriodFrequency");

    /// <summary>ContractSettings: id = "closurePermissionPeriodFrequency" (line 4147) — globally unique.</summary>
    public ILocator ClosurePermissionPeriodFrequency => _page.Locator("#closurePermissionPeriodFrequency");

    /// <summary>ContractSettings: id = "supportEvidenceGracePeriodFrequency" (line 4230) — globally unique.</summary>
    public ILocator SupportEvidenceGracePeriodFrequency => _page.Locator("#supportEvidenceGracePeriodFrequency");

    /// <summary>ContractSettings: id = "supportClosurePermissionPeriodFrequency" (line 4306) — globally unique.</summary>
    public ILocator SupportClosurePermissionPeriodFrequency => _page.Locator("#supportClosurePermissionPeriodFrequency");

    /// <summary>ContractSettings: id = "merchant-settings" (line 4366) — globally unique.</summary>
    public ILocator MerchantSettings => _page.Locator("#merchant-settings");

    /// <summary>ContractSettings: id = "unique-reference-numbers" (line 4728) — globally unique.</summary>
    public ILocator UniqueReferenceNumbers => _page.Locator("#unique-reference-numbers");

    /// <summary>ContractSettings: id = "usrn" (line 4739) — globally unique.</summary>
    public ILocator Usrn => _page.Locator("#usrn");

    /// <summary>ContractSettings: id = "uprn" (line 4761) — globally unique.</summary>
    public ILocator Uprn => _page.Locator("#uprn");

    /// <summary>ContractSettings: id = "pricing-alert-configuration" (line 4778) — globally unique.</summary>
    public ILocator PricingAlertConfiguration => _page.Locator("#pricing-alert-configuration");

    /// <summary>ContractSettings: id = "firstFrequency" (line 4808) — globally unique.</summary>
    public ILocator FirstFrequency => _page.Locator("#firstFrequency");

    /// <summary>ContractSettings: id = "secondFrequency" (line 4887) — globally unique.</summary>
    public ILocator SecondFrequency => _page.Locator("#secondFrequency");

    /// <summary>ContractSettings: id = "visitor-portal-settings" (line 4985) — globally unique.</summary>
    public ILocator VisitorPortalSettings => _page.Locator("#visitor-portal-settings");

    /// <summary>ContractSettings: id = "suspension-settings" (line 5040) — globally unique.</summary>
    public ILocator SuspensionSettings => _page.Locator("#suspension-settings");

    /// <summary>ContractSettings: id = "suspensionTownField" (line 5063) — globally unique.</summary>
    public ILocator SuspensionTownField => _page.Locator("#suspensionTownField");

    /// <summary>ContractSettings: id = "isMaxSuspensionsPerStreetEnabled" (line 5097) — globally unique.</summary>
    public ILocator IsMaxSuspensionsPerStreetEnabled => _page.Locator("#isMaxSuspensionsPerStreetEnabled");

    /// <summary>ContractSettings: id = "suspensionsLimit" (line 5142) — globally unique.</summary>
    public ILocator SuspensionsLimit => _page.Locator("#suspensionsLimit");

    /// <summary>ContractSettings: id = "dispensation-settings" (line 5222) — globally unique.</summary>
    public ILocator DispensationSettings => _page.Locator("#dispensation-settings");

    /// <summary>ContractSettings: id = "isDispensationTownFieldEnabled" (line 5243) — globally unique.</summary>
    public ILocator IsDispensationTownFieldEnabled => _page.Locator("#isDispensationTownFieldEnabled");

    /// <summary>ContractSettings: id = "isMaxDispensationsPerStreetEnabled" (line 5268) — globally unique.</summary>
    public ILocator IsMaxDispensationsPerStreetEnabled => _page.Locator("#isMaxDispensationsPerStreetEnabled");

    /// <summary>ContractSettings: id = "dispensationsLimit" (line 5315) — globally unique.</summary>
    public ILocator DispensationsLimit => _page.Locator("#dispensationsLimit");

    /// <summary>ContractSettings: id = "others" (line 5387) — globally unique.</summary>
    public ILocator Others => _page.Locator("#others");

    /// <summary>ContractSettings: id = "isSMSReminder" (line 5402) — globally unique.</summary>
    public ILocator IsSMSReminder => _page.Locator("#isSMSReminder");

    /// <summary>ContractSettings: id = "isEmailCommunication" (line 5431) — globally unique.</summary>
    public ILocator IsEmailCommunication => _page.Locator("#isEmailCommunication");

    /// <summary>ContractSettings: id = "isDieselSurcharge" (line 5459) — globally unique.</summary>
    public ILocator IsDieselSurcharge => _page.Locator("#isDieselSurcharge");

    /// <summary>ContractSettings: id = "isTierPricing" (line 5485) — globally unique.</summary>
    public ILocator IsTierPricing => _page.Locator("#isTierPricing");

    /// <summary>ContractSettings: id = "iskeepTierPriceAtOriginalRate" (line 5514) — globally unique.</summary>
    public ILocator IskeepTierPriceAtOriginalRate => _page.Locator("#iskeepTierPriceAtOriginalRate");

    /// <summary>ContractSettings: id = "isAddressChallengeEnabled" (line 5542) — globally unique.</summary>
    public ILocator IsAddressChallengeEnabled => _page.Locator("#isAddressChallengeEnabled");

    /// <summary>ContractSettings: id = "isRedactRetentionPeriod" (line 5597) — globally unique.</summary>
    public ILocator IsRedactRetentionPeriod => _page.Locator("#isRedactRetentionPeriod");

    /// <summary>ContractSettings: id = "redactRetentionReminderFrequency" (line 5625) — globally unique.</summary>
    public ILocator RedactRetentionReminderFrequency => _page.Locator("#redactRetentionReminderFrequency");

    /// <summary>ContractSettings: placeholder = "Period" (line 5673) — globally unique.</summary>
    public ILocator Period => _page.Locator("[placeholder='Period']");

    /// <summary>ContractSettings: placeholder = "Select" (line 5731) — globally unique.</summary>
    public ILocator Select => _page.Locator("[placeholder='Select']");

    /// <summary>ContractSettings: id = "experianOperatesText" (line 5742) — globally unique.</summary>
    public ILocator ExperianOperatesText => _page.Locator("#experianOperatesText");

    /// <summary>ContractSettings: placeholder = "0" (line 5771) — globally unique.</summary>
    public ILocator _0 => _page.Locator("[placeholder='0']");

    /// <summary>ContractSettings: data-testid = "unsaved-dialog-close" (line 5841) — globally unique.</summary>
    public ILocator UnsavedDialogClose => _page.Locator("[data-testid='unsaved-dialog-close']");

}